### PR TITLE
Fix false positives in redundant_discardable_let rule

### LINKED ISSUE #6063: False positive on `redundant_discardable_let` rule in SwiftUI `@ViewBuilder`
### New Issue Checklist

- [ x ] I've Updated SwiftLint to the latest version.
- [ x ] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

The rule `redundant_discardable_let` is falsely triggered inside SwiftUI `@ViewBuilder` implementation, although the option `ignore_swiftui_view_bodies` is set to `true`.
Using the `--fix` option for this violation will remove the `let`, and previews won't compile. The option is working properly inside SwiftUI `var body: some View` declarations.

```swift
// This triggers a violation:
@ViewBuilder
func viewBuilder() -> some View {
    let _ = "Test Builder"
    EmptyView()
}
```
Removing the `let` will break the `View` conformance. Adding explicit `return` to `EmptyView` will break the result builder `ViewBuilder`.

```bash
$ swiftlint --strict --progress

TestFile.swift:60:9: error: Redundant Discardable Let Violation: Prefer `_ = foo()` over `let _ = foo()` when discarding a result from a function (redundant_discardable_let)
```

### Environment

* SwiftLint version: 0.59.1
* Xcode version: Xcode 16.2, Build version 16C5032a
* Installation via Homebrew
* Configuration file:

```yml
# Default rule configuration
redundant_discardable_let:
    ignore_swiftui_view_bodies: true
```

No nested configurations.

Imho the exception for `var body: some View` should also apply to `@ViewBuilder` implementations since they follow the same rules as the `var body: some View` declarations.

### PR DESCRIPTION
**Pull request by kaseken**
Fixes #6063

I’d appreciate any feedback or suggestions.  Thanks in advance for your time and review!

#### Changes

- Fix false positive for `@ViewBuilder` functions when ignore_swiftui_view_bodies is set to true.
- Fix false positive for #Preview when ignore_swiftui_view_bodies is set to true.
- Fix false positive for PreviewProvider when ignore_swiftui_view_bodies is set to true.

### CODE REVIEW

**Comment by kaseken** [comment]
buildkite/swiftlint seems to be failing due to the following issue:
https://github.com/realm/SwiftLint/issues/6076

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 1]
```diff
@@ -32,6 +51,25 @@ struct RedundantDiscardableLetRule: Rule {
                     Text("Hello, World!")
                 }
                 """),
+            Example("""
+                @ViewBuilder
+                func bar() -> some View {
+                    let _ = foo()
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Please add violation markers `↓` to the added triggering examples:
```suggestion
                    ↓let _ = foo()
```

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 2]
```diff
@@ -100,4 +147,56 @@ private extension AccessorBlockSyntax {
...
+    var isPreviewProviderBody: Bool {
+        guard let binding = parent?.as(PatternBindingSyntax.self),
+              binding.pattern.as(IdentifierPatternSyntax.self)?.identifier.text == "previews",
+              let bindingList = binding.parent?.as(PatternBindingListSyntax.self),
+              let variableDecl = bindingList.parent?.as(VariableDeclSyntax.self) else {
+            return false
+        }
+
+        guard variableDecl.modifiers.contains(keyword: .static) &&
+                variableDecl.bindingSpecifier.tokenKind == .keyword(.var) else {
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]:
```suggestion
        guard variableDecl.modifiers.contains(keyword: .static),
              variableDecl.bindingSpecifier.tokenKind == .keyword(.var) else {
```

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 3]
```diff
@@ -100,4 +147,56 @@ private extension AccessorBlockSyntax {
...
+            return false
+        }
+
+        if let type = binding.typeAnnotation?.type.as(SomeOrAnyTypeSyntax.self) {
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Maybe is a `guard` as well. Then you can even combine all guards into one.

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 4]
```diff
@@ -100,4 +147,56 @@ private extension AccessorBlockSyntax {
...
+}
+
+private extension CodeBlockSyntax {
+    var isViewBuilderFunctionBody: Bool {
+        parent?.as(FunctionDeclSyntax.self)?.isViewBuilderFunction == true
+    }
+}
+
+private extension FunctionDeclSyntax {
+    var isViewBuilderFunction: Bool {
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Could be inlined into `isViewBuilderFunctionBody`.

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 5]
```diff
@@ -100,4 +147,56 @@ private extension AccessorBlockSyntax {
...
+        guard attributes.contains(attributeNamed: "ViewBuilder") else {
+            return false
+        }
+
+        guard let returnType = signature.returnClause?.type.as(SomeOrAnyTypeSyntax.self) else {
+            return false
+        }
+
+        return returnType.someOrAnySpecifier.text == "some" &&
+            returnType.constraint.as(IdentifierTypeSyntax.self)?.name.text == "View"
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: This could be a computed property on `SomeOrAnyTypeSyntax` to avoid the duplication.

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 6]
```diff
@@ -100,4 +147,56 @@ private extension AccessorBlockSyntax {
...
+    }
+}
+
+private extension ClosureExprSyntax {
+    var isPreviewMacroBody: Bool {
+        if let macroExpansionExpr = parent?.as(MacroExpansionExprSyntax.self),
+           macroExpansionExpr.macroName.text == "Preview" {
+            return true
+        }
+        return false
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]:
```suggestion
        parent?.as(MacroExpansionExprSyntax.self)?.macroName.text == "Preview"
```

File: CHANGELOG.md [hunk 7]
```diff
@@ -18,7 +18,8 @@
 
 ### Bug Fixes
 
-* None.
+* Fix false positives in `redundant_discardable_let` when `ignore_swiftui_view_bodies` is enabled.
```
Comment (SimplyDanny) [inline CHANGELOG.md]: Please append two spaces to the end of the description. They are required to enforce a line break in the rendered Markdown:
```suggestion
* Fix false positives of `redundant_discardable_let` rule in `@ViewBuilder` functions,
  `#Preview` macro bodies and preview provides when `ignore_swiftui_view_bodies` is
  enabled.  
```

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 8]
```diff
@@ -32,6 +51,25 @@ struct RedundantDiscardableLetRule: Rule {
...
+                """),
+            Example("""
+                static var previews: some View {
+                    let _ = foo()
+                    Text("Hello, World!")
+                }
+                """),
         ],
         corrections: [
             Example("↓let _ = foo()"): Example("_ = foo()"),
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift:87]: Let's also add a correction test example.

**Review by SimplyDanny — CHANGES_REQUESTED** [review]
Thank you for the contribution! The implementation looks very good already. 👍 

My comments are mainly about style and consistency. Please have a look.

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift (hunk 1 above)
Comment (kaseken) [reply Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Fixed here: https://github.com/realm/SwiftLint/pull/6075/commits/266b52af40163cc0c35274e08127b42b4069a378

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift (hunk 2 above)
Comment (kaseken) [reply Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Fixed here: https://github.com/realm/SwiftLint/pull/6075/commits/b8e67bff3a616dfc8a9df6d65155074a66a4a2fe

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift (hunk 3 above)
Comment (kaseken) [reply Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Combined into a single guard here: https://github.com/realm/SwiftLint/pull/6075/commits/b8e67bff3a616dfc8a9df6d65155074a66a4a2fe

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift (hunk 6 above)
Comment (kaseken) [reply Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Fixed here: https://github.com/realm/SwiftLint/pull/6075/commits/bdc4cf97af328788ba8e34a4f4bc7b0237511f5c

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift (hunk 5 above)
Comment (kaseken) [reply Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Fixed here: https://github.com/realm/SwiftLint/pull/6075/commits/5e364e7cf1446aad3f38e47acad47989bab42762

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift (hunk 4 above)
Comment (kaseken) [reply Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift]: Fixed here: https://github.com/realm/SwiftLint/pull/6075/commits/8538ccb55f50f08344a02296fb8da82832383553

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift (hunk 8 above)
Comment (kaseken) [reply Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift:87]: Fixed here: https://github.com/realm/SwiftLint/pull/6075/commits/699a6582558b9f56b5ee8b4797e9dcd9a7e85ed2

File: CHANGELOG.md (hunk 7 above)
Comment (kaseken) [reply CHANGELOG.md]: Fixed here: https://github.com/realm/SwiftLint/pull/6075/commits/ce8053605dd8dadf3984c7753b16347d1715f655

**Comment by kaseken** [comment]
@SimplyDanny Thank you for your thorough review!

I've incorporated all of your suggestions.

Additionally, I’ve added more triggeringExamples as unit tests to further ensure that the added `isPreviewProviderBody` isn’t causing any issues.
https://github.com/realm/SwiftLint/pull/6075/commits/00866da6a0fc1e55c7bc16c25794080600b31fa9

I’d appreciate it if you could take another look when you have time. Thanks in advance!

File: CHANGELOG.md [hunk 9]
```diff
@@ -24,6 +24,10 @@
   or other error.  
   [Martin Redington](https://github.com/mildm8nnered)
   [#6052](https://github.com/realm/SwiftLint/issues/6052)
+* Fix false positives of `redundant_discardable_let` rule in `@ViewBuilder` functions,
+  `#Preview` macro bodies and preview provides when `ignore_swiftui_view_bodies` is
+  enabled.  
+  [kaseken](https://github.com/kaseken)
```
Comment (SimplyDanny) [inline CHANGELOG.md]: Please add a link to the issue as well.

File: CHANGELOG.md [hunk 10]
```diff
@@ -24,6 +24,10 @@
   or other error.  
   [Martin Redington](https://github.com/mildm8nnered)
   [#6052](https://github.com/realm/SwiftLint/issues/6052)
+* Fix false positives of `redundant_discardable_let` rule in `@ViewBuilder` functions,
```
Comment (SimplyDanny) [inline CHANGELOG.md]: Needs an empty line above.

Also I think this should go into the "Enhancements" section.

File: CHANGELOG.md [hunk 11]
```diff
@@ -24,6 +24,10 @@
...
+  `#Preview` macro bodies and preview provides when `ignore_swiftui_view_bodies` is
```
Comment (SimplyDanny) [inline CHANGELOG.md]:
```suggestion
  `#Preview` macro bodies and preview providers when `ignore_swiftui_view_bodies` is
```

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 12]
```diff
@@ -32,10 +51,87 @@ struct RedundantDiscardableLetRule: Rule {
...
+                    ↓let _ = foo()
+                    Text("Hello, World!")
+                }
+                """, configuration: ["ignore_swiftui_view_bodies": true], excludeFromDocumentation: true),
+            Example("""
+                var body: some NotView {
+                    ↓let _ = foo()
+                    Text("Hello, World!")
+                }
+                """, configuration: ["ignore_swiftui_view_bodies": true], excludeFromDocumentation: true),
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift:84]: 👍

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift [hunk 13]
```diff
@@ -32,10 +51,87 @@ struct RedundantDiscardableLetRule: Rule {
...
+                static var previews: some View {
+                    ↓let _ = foo()
+                    Text("Hello, World!")
+                }
+                """): Example("""
+                    static var previews: some View {
+                        _ = foo()
+                        Text("Hello, World!")
+                    }
+                    """),
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift:121]: I think that two examples are enough to show that corrections work. Please consider adding another example with the option enabled to show that no correction would be applied.

**Review by SimplyDanny — COMMENTED** [review]
Thanks for the updates. There are a few more points to consider.

File: CHANGELOG.md (hunk 9 above)
Comment (kaseken) [reply CHANGELOG.md]: Added issue link here: https://github.com/realm/SwiftLint/pull/6075/commits/3da5c81f8282731a88fe33c5349c8fa8939fd006

File: CHANGELOG.md (hunk 10 above)
Comment (kaseken) [reply CHANGELOG.md]: Added empty line and moved to enhancements section here.
https://github.com/realm/SwiftLint/pull/6075/commits/3da5c81f8282731a88fe33c5349c8fa8939fd006

File: CHANGELOG.md (hunk 9 above)
Comment (kaseken) [reply CHANGELOG.md]: Added issue link.
https://github.com/realm/SwiftLint/pull/6075/commits/103a1c079bf45046ef3ce5872ed63cb58532099a

File: CHANGELOG.md (hunk 10 above)
Comment (kaseken) [reply CHANGELOG.md]: Added empty line and moved to the "Enhancements" section.
https://github.com/realm/SwiftLint/pull/6075/commits/103a1c079bf45046ef3ce5872ed63cb58532099a

File: CHANGELOG.md (hunk 11 above)
Comment (kaseken) [reply CHANGELOG.md]: Fixed typo.
https://github.com/realm/SwiftLint/pull/6075/commits/103a1c079bf45046ef3ce5872ed63cb58532099a

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift (hunk 13 above)
Comment (kaseken) [reply Source/SwiftLintBuiltInRules/Rules/Style/RedundantDiscardableLetRule.swift:121]: I kept the corrections using `var body: some View` and the `#Preview` macro, since they are commonly used, and removed the other examples.
I have also added a example with "ignore_swiftui_view_bodies" set to true, and with no corrections.

https://github.com/realm/SwiftLint/pull/6075/commits/e45e556f3ced79c46d02e52032c59825096399a1

**Comment by kaseken** [comment]
@SimplyDanny Thanks for reviewing!  I've fixed all the issues.

Some CI jobs ('buildkite/swiftlint' and ''buildkite/swiftlint/danger') seems to be failing due to an error unrelated to this PR.
https://buildkite.com/swiftlint/swiftlint/builds/9882

Maybe the `DANGER_GITHUB_API_TOKEN` has expired?

```sh
bundle exec danger --verbose
--
  | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  | bundler: failed to load command: danger (/Users/administrator/.rbenv/versions/3.4.2/bin/danger)
  | /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/octokit-5.6.1/lib/octokit/response/raise_error.rb:14:in 'Octokit::Response::RaiseError#on_complete': GET https://api.github.com/repos/realm/SwiftLint/pulls/6075: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/faraday-2.7.4/lib/faraday/middleware.rb:18:in 'block in Faraday::Middleware#call'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/faraday-2.7.4/lib/faraday/response.rb:42:in 'Faraday::Response#on_complete'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/faraday-2.7.4/lib/faraday/middleware.rb:17:in 'Faraday::Middleware#call'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/octokit-5.6.1/lib/octokit/middleware/follow_redirects.rb:73:in 'Octokit::Middleware::FollowRedirects#perform_with_redirection'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/octokit-5.6.1/lib/octokit/middleware/follow_redirects.rb:61:in 'Octokit::Middleware::FollowRedirects#call'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/faraday-2.7.4/lib/faraday/rack_builder.rb:153:in 'Faraday::RackBuilder#build_response'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/faraday-2.7.4/lib/faraday/connection.rb:444:in 'Faraday::Connection#run_request'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/faraday-2.7.4/lib/faraday/connection.rb:200:in 'Faraday::Connection#get'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in 'Sawyer::Agent#call'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/octokit-5.6.1/lib/octokit/connection.rb:156:in 'Octokit::Connection#request'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/octokit-5.6.1/lib/octokit/connection.rb:19:in 'Octokit::Connection#get'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/octokit-5.6.1/lib/octokit/client/pull_requests.rb:33:in 'Octokit::Client::PullRequests#pull_request'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/danger-9.2.0/lib/danger/request_sources/github/github.rb:117:in 'Danger::RequestSources::GitHub#fetch_details'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/danger-9.2.0/lib/danger/danger_core/environment_manager.rb:53:in 'Danger::EnvironmentManager#fill_environment_vars'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/danger-9.2.0/lib/danger/danger_core/dangerfile.rb:280:in 'Danger::Dangerfile#run'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/danger-9.2.0/lib/danger/danger_core/executor.rb:28:in 'Danger::Executor#run'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/danger-9.2.0/lib/danger/commands/runner.rb:73:in 'Danger::Runner#run'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/claide-1.1.0/lib/claide/command.rb:334:in 'CLAide::Command.run'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/danger-9.2.0/bin/danger:5:in '<top (required)>'
  | from /Users/administrator/.rbenv/versions/3.4.2/bin/danger:25:in 'Kernel#load'
  | from /Users/administrator/.rbenv/versions/3.4.2/bin/danger:25:in '<top (required)>'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in 'Kernel.load'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in 'Bundler::CLI#exec'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'Bundler::Thor::Command#run'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in 'Bundler::Thor.dispatch'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in 'Bundler::CLI.dispatch'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'Bundler::Thor::Base::ClassMethods#start'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in 'Bundler::CLI.start'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/exe/bundle:45:in 'block in <top (required)>'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
  | from /Users/administrator/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/bundler-2.4.12/exe/bundle:33:in '<top (required)>'
  | from /Users/administrator/.rbenv/versions/3.4.2/bin/bundle:25:in 'Kernel#load'
  | from /Users/administrator/.rbenv/versions/3.4.2/bin/bundle:25:in '<main>'
  | make: *** [oss_scan] Error 1
  | 🚨 Error: The command exited with status 2
  | user command error: exit status 2
```
