### PR TITLE
Fixing false positives in operator_usage_whitespace

### LINKED ISSUE #989: operator_usage_whitespace doesn't trigger if operand has parentheses
Examples:

```swift
let v8 = Int8(1)  << 6
let v8 = 1 <<  (6)
```

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #989

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/OperatorUsageWhitespaceRule.swift [hunk 1]
```diff
@@ -61,18 +66,19 @@ public struct OperatorUsageWhitespaceRule: OptInRule, ConfigurationProviderRule
...
         let patterns = spaces.map { first, second in
-            variableOrNumber + first + operators + second + variableOrNumber
+            leadingVariableOrNumber + first + operators + second + trailingVariableOrNumber
         }
         let pattern = "(?:\(patterns.joined(separator: "|")))"
 
-        let genericPattern = "<.+?>"
-        let validRangePattern = variableOrNumber + zeroSpaces + rangePattern +
-            zeroSpaces + variableOrNumber
+        let genericPattern = "<(?:\(oneSpace)|\\S)+?>" // not using dot to avoid matching new line
```
Comment (marcelofabri) [inline Source/SwiftLintFramework/Rules/OperatorUsageWhitespaceRule.swift]: this still can prevent some violations if there's `>` on the same line, for example:
```swift
method(1 <<   (6), otherParam: 1 > 2)
```

🐛

**Comment by jpsim** [comment]
👍
