### PR TITLE
Fixes warning about configurations for rules that are not enabled, when they are enabled in a parent config

### LINKED ISSUE #4858: Incorrect warning for `Found a configuration for 'some_rule' rule, but it is not enabled on 'opt_in_rules'.` with `parent_config`'s
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

All examples run from the top of the SwiftLint source tree.

I made a new configuration file:

```
% cat .swiftlint-new.yml 
included:
  - Plugins
  - Source
  - Tests
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
opt_in_rules:
  - implicit_return
disabled_rules:
  - type_body_length
  - function_body_length
  - large_tuple

implicit_return:
  included:
    - closure
#   - function
#   - getter
```

Running it from the top of the tree:

```
% swiftlint --config .swiftlint-new.yml  --reporter summary --quiet
+-----------------+--------+-------------+--------+----------+--------+------------------+-----------------+
| rule identifier | opt-in | correctable | custom | warnings | errors | total violations | number of files |
+-----------------+--------+-------------+--------+----------+--------+------------------+-----------------+
| implicit_return | yes    | yes         | no     |       59 |      0 |               59 |              36 |
+-----------------+--------+-------------+--------+----------+--------+------------------+-----------------+
| Total           |        |             |        |       59 |      0 |               59 |              36 |
+-----------------+--------+-------------+--------+----------+--------+------------------+-----------------+
```

Now I add a new configuration, whose parent is the one I just created, but which is stricter about the settings for `implicit_return`:

```
% cat .swiftlint-child.yml
parent_config: .swiftlint-new.yml

implicit_return:
  included:
    - closure
    - function
    - getter
```

Running SwiftLint against this config:

```
warning: Found a configuration for 'implicit_return' rule, but it is not enabled on 'opt_in_rules'.
+-----------------+--------+-------------+--------+----------+--------+------------------+-----------------+
| rule identifier | opt-in | correctable | custom | warnings | errors | total violations | number of files |
+-----------------+--------+-------------+--------+----------+--------+------------------+-----------------+
| implicit_return | yes    | yes         | no     |      448 |      0 |              448 |             200 |
+-----------------+--------+-------------+--------+----------+--------+------------------+-----------------+
| Total           |        |             |        |      448 |      0 |              448 |             200 |
+-----------------+--------+-------------+--------+----------+--------+------------------+-----------------+
```

`rules` also produces the warning, but indicates that the new configuration is applied:

```
% swiftlint  rules --config .swiftlint-child.yml                            
warning: Found a configuration for 'implicit_return' rule, but it is not enabled on 'opt_in_rules'.
+------------------------------------------+--------+-------------+------------------------+-------------+----------+----------------+---------------------------------------------------------------------------------------+
| identifier                               | opt-in | correctable | enabled in your config | kind        | analyzer | uses sourcekit | configuration                                                                         |
+------------------------------------------+--------+-------------+------------------------+-------------+----------+----------------+---------------------------------------------------------------------------------------+
| implicit_return                          | yes    | yes         | yes                    | style       | no       | yes            | severity: warning, included: [closure, function, getter]                              |
+------------------------------------------+--------+-------------+------------------------+-------------+----------+----------------+---------------------------------------------------------------------------------------+
```

Expected: if the rule is enabled, even in another config, the warning should not be displayed.

##### Complete output when running SwiftLint, including the stack trace and command used

See above:

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.51.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

See above

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.

No, but parent_config yes - see description above

* Which Xcode version are you using (check `xcodebuild -version`)?

```
Xcode 14.2
Build version 14C18
```

* Do you have a sample that shows the issue? 

See description above.

### PR DESCRIPTION
**Pull request by mildm8nnered**
Fixes #4858

The problem here is configurations like this:

```
included:
  - Plugins
  - Source
  - Tests
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
opt_in_rules:
  - implicit_return
disabled_rules:
  - type_body_length
  - function_body_length
  - large_tuple

implicit_return:
  included:
    - closure
```

with child configurations like this:

```
parent_config: .swiftlint-parent.yml

implicit_return:
  included:
    - closure
    - function
    - getter
```

SwiftLint will report `warning: Found a configuration for 'implicit_return' rule, but it is not enabled on 'opt_in_rules'.` for the child config, even though it will correctly apply the new config.

We now pass in the parent configuration when validating rule configurations for the child, and do not complain about configurations where that rule is enabled in the parent.

There should be no change in behaviour at all here - just a change in the warnings.

Getting this correct turned out to be quite complex, but after this PR, it should be the case that whenever, and only when, a rule is disabled in the parent or "child" config, a warning message will be printed, and the exact warning will vary somewhat, depending on whether the rule is disabled in the parent or "child", or not enabled at all.

There is a separate issue with `child_config` that this PR does not attempt to address - See #5251

### CODE REVIEW

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift [hunk 1]
```diff
@@ -194,14 +199,43 @@ extension Configuration {
...
-                        "'\(Key.optInRules.rawValue)'.")
-                } else if Set(disabledRules).isSuperset(of: rule.description.allIdentifiers) {
-                    queuedPrintError("\(message), but it is disabled on " +
-                        "'\(Key.disabledRules.rawValue)'.")
+                validateConfiguredRulesAreEnabled(
+                    message: message,
+                    parentConfiguration: parentConfiguration,
+                    disabledRules: disabledRules,
+                    optInRules: optInRules,
+                    rule: rule
```
Comment (SimplyDanny) [inline Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift:207]: Better to name `ruleType`:
```suggestion
                    ruleType: ruleType
```

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift [hunk 2]
```diff
@@ -194,14 +199,43 @@ extension Configuration {
...
+                )
+            }
+        }
+    }
+
+    private static func validateConfiguredRulesAreEnabled(
```
Comment (SimplyDanny) [inline Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift:213]: It's only one rule that's validated:
```suggestion
    private static func validateConfiguredRuleIsEnabled(
```

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift [hunk 3]
```diff
@@ -194,14 +199,43 @@ extension Configuration {
...
+        disabledRules: Set<String>,
+        optInRules: Set<String>,
+        rule: Rule.Type
+    ) {
+        if rule is OptInRule.Type {
+            var allOptInRules = optInRules
+            if let parentConfiguration {
+                switch parentConfiguration.rulesMode {
+                case .allEnabled:
+                    return
```
Comment (SimplyDanny) [inline Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift:225]: Don't we have to check here that all rules minus the rules disabled in the child configuration contain the rule's ID?

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift [hunk 4]
```diff
@@ -194,14 +199,43 @@ extension Configuration {
...
+                case .only(let parentOnlyRules):
+                    allOptInRules.formUnion(parentOnlyRules)
```
Comment (SimplyDanny) [inline Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift:227]: Same here: Don't we have to subtract the rules disabled in the child configuration?

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift [hunk 5]
```diff
@@ -194,14 +199,43 @@ extension Configuration {
...
+                case let .default(disabled: _, optIn: parentOptInRules):
+                    allOptInRules.formUnion(parentOptInRules)
```
Comment (SimplyDanny) [inline Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift:229]: Same here.

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift [hunk 6]
```diff
@@ -194,14 +199,43 @@ extension Configuration {
...
                 }
             }
+            if Set(allOptInRules).isDisjoint(with: rule.description.allIdentifiers) {
+                queuedPrintError("\(message), but it is not enabled on " +
+                                 "'\(Key.optInRules.rawValue)'.")
+            }
+        } else if Set(disabledRules).isSuperset(of: rule.description.allIdentifiers) {
```
Comment (SimplyDanny) [inline Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift:236]: Rules could also be disabled in the parent.

**Review by SimplyDanny — COMMENTED** [review]
I lost a bit the the overview. Perhaps my comments/questions are stupid. But somehow the disabled rules must be taken into account, isn't it?

**Comment by mildm8nnered** [comment]
> I lost a bit the the overview. Perhaps my comments/questions are stupid. But somehow the disabled rules must be taken into account, isn't it?

I think you're right about disabled - I'll put together some local test cases to verify those, athough I'll try to find a configurable non-optin rule to test with because of https://github.com/realm/SwiftLint/issues/4859

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift (hunk 6 above)
Comment (mildm8nnered) [reply Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift]: So I think I've taken care of the parent case now, where, for example

```
included:
  - Source
disabled_rules:
  - blanket_disable_command
```

and

```
parent_config: .swiftlint-new.yml

blanket_disable_command:
  always_allow: [file_header, file_length, file_name, file_name_no_space, single_test_class]
```

which I have producing 

`warning: Found a configuration for 'blanket_disable_command' rule, but it is disabled in a parent configuration.`

I'm going to need to take a look at the other cases in more detail, so I'm going to move this back to draft for now. They're basically the inverse of the original bug in a way.

It would be great to have a way to unit test these, as the logic is actually quite complex.

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift (hunk 3 above)
Comment (mildm8nnered) [reply Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift:225]: So yes, but #4859 means that opt-in rules cannot be disabled in a child configuration in some circumstances, which may change the calculation slightly.

I have a fix for that at #4863, which seems right, but I'm still not sure the current behaviour is intentional somehow.

**Comment by mildm8nnered** [comment]
> I lost a bit the overview. Perhaps my comments/questions are stupid. But somehow the disabled rules must be taken into account, isn't it?

Yep - I definitely was missing some cases before. I think I should have them all covered now.

File: Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift (hunk 3 above)
Comment (mildm8nnered) [reply Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift]: This should now be resolved

File: Source/SwiftLintCore/Extensions/Configuration+Parsing.swift [hunk 7]
```diff
@@ -147,35 +152,104 @@ extension Configuration {
...
+                issue?.print()
             case let .default(disabled: disabledRules, optIn: optInRules):
-                if rule is any OptInRule.Type, Set(optInRules).isDisjoint(with: rule.description.allIdentifiers) {
-                    Issue.genericWarning("\(message), but it is not enabled on '\(Key.optInRules.rawValue)'.").print()
-                } else if Set(disabledRules).isSuperset(of: rule.description.allIdentifiers) {
-                    Issue.genericWarning("\(message), but it is disabled on '\(Key.disabledRules.rawValue)'.").print()
+                let issue = validateConfiguredRuleIsEnabled(
+                    parentConfiguration: parentConfiguration,
+                    enabledInParentRules: enabledInParentRules,
+                    disabledInParentRules: disabledInParentRules,
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Extensions/Configuration+Parsing.swift:194]: The precalculated sets are only needed here, aren't they? If so, let's only compute them here when they are needed.

File: Source/SwiftLintCore/Models/Issue.swift [hunk 8]
```diff
@@ -20,6 +20,21 @@ public enum Issue: LocalizedError, Equatable {
     /// Used rule IDs are invalid.
     case invalidRuleIDs(Set<String>)
 
+    /// Found a rule configuration for a rule that is not present in only_rules.
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Models/Issue.swift:23]:
```suggestion
    /// Found a rule configuration for a rule that is not present in `only_rules`.
```

File: Source/SwiftLintCore/Models/Issue.swift [hunk 9]
```diff
@@ -20,6 +20,21 @@ public enum Issue: LocalizedError, Equatable {
...
+    case ruleNotPresentInOnlyRules(ruleID: String)
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Models/Issue.swift:24]: The issues are about the configuration, aren't they?
```suggestion
    case configurationForRuleNotPresentInOnlyRules(ruleID: String)
```

File: Source/SwiftLintCore/Models/Issue.swift [hunk 10]
```diff
@@ -20,6 +20,21 @@ public enum Issue: LocalizedError, Equatable {
...
+
+    /// Found a rule configuration for a rule that is disabled.
+    case ruleDisabledInDisabledRules(ruleID: String)
+
+    /// Found a rule configuration for a rule that is disabled in the parent configuration
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Models/Issue.swift:29]:
```suggestion
    /// Found a rule configuration for a rule that is disabled in the parent configuration.
```

File: Source/SwiftLintCore/Models/Issue.swift [hunk 11]
```diff
@@ -20,6 +20,21 @@ public enum Issue: LocalizedError, Equatable {
...
+    case ruleDisabledInParentConfiguration(ruleID: String)
+
+    /// Found a rule configuration for a rule that is not enabled in opt_in_rules
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Models/Issue.swift:32]:
```suggestion
    /// Found a rule configuration for a rule that is not enabled in `opt_in_rules`.
```

File: Source/SwiftLintCore/Models/Issue.swift [hunk 12]
```diff
@@ -20,6 +20,21 @@ public enum Issue: LocalizedError, Equatable {
...
+    case ruleNotEnabledInOptInRules(ruleID: String)
+
+    /// Found a rule configuration for a rule that is not enabled in parent only_rules.
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Models/Issue.swift:35]:
```suggestion
    /// Found a rule configuration for a rule that is not enabled in parent `only_rules`.
```

File: Source/SwiftLintCore/Models/Issue.swift [hunk 13]
```diff
@@ -101,6 +116,20 @@ public enum Issue: LocalizedError, Equatable {
             return "Configuration for '\(id)' rule contains the invalid key(s) \(keys.formatted)."
         case let .invalidRuleIDs(ruleIDs):
             return "The key(s) \(ruleIDs.formatted) used as rule identifier(s) is/are invalid."
+        case let .ruleNotPresentInOnlyRules(id):
+            return "Found a configuration for '\(id)' rule, but it is not present on " +
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Models/Issue.swift:120]: **On** or **in** `only_rules`?

File: Source/SwiftLintCore/Models/Issue.swift [hunk 14]
```diff
@@ -101,6 +116,20 @@ public enum Issue: LocalizedError, Equatable {
...
+        case let .ruleDisabledInDisabledRules(id):
+            return "Found a configuration for '\(id)' rule, but it is disabled on " +
+                   "'\(Configuration.Key.disabledRules.rawValue)'."
+        case let .ruleDisabledInParentConfiguration(id):
+            return "Found a configuration for '\(id)' rule, but it is disabled in a parent configuration."
+        case let .ruleNotEnabledInOptInRules(id):
+            return "Found a configuration for '\(id)' rule, but it is not enabled on " +
+                   "'\(Configuration.Key.optInRules.rawValue)'."
+        case let .ruleNotEnabledInParentOnlyRules(id):
+            return "Found a configuration for '\(id)' rule, but it is not present in the parent " +
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Models/Issue.swift:131]: Is that more correct?
```suggestion
            return "Found a configuration for '\(id)' rule, but it is not present in the parent's " +
```

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift [hunk 15]
```diff
@@ -411,12 +411,158 @@ extension ConfigurationTests {
...
+        XCTAssertTrue((optInRuleType as Any) is any OptInRule.Type)
+        testDefaultConfigurationDisabledRuleWarnings(for: optInRuleType)
+
+        let defaultRuleType = BlockBasedKVORule.self
+        XCTAssertFalse((defaultRuleType as Any) is any OptInRule.Type)
+        testDefaultConfigurationDisabledRuleWarnings(for: defaultRuleType)
+    }
+
+    private func testDefaultConfigurationDisabledRuleWarnings(for ruleType: any Rule.Type) {
+        let ruleType = ImplicitReturnRule.self
```
Comment (SimplyDanny) [inline Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift:432]: This overrides the argument.

File: CHANGELOG.md [hunk 16]
```diff
@@ -163,6 +168,7 @@
   [SimplyDanny](https://github.com/SimplyDanny)
   [#5277](https://github.com/realm/SwiftLint/issues/5277)
 
+* Fix false positive in `unused_import` rule that triggered on
```
Comment (SimplyDanny) [inline CHANGELOG.md:171]: Duplicate.

**Review by SimplyDanny — CHANGES_REQUESTED** [review]
Sorry for the very late feedback! This is a quite complex topic which scares me off a little. 😅

I have some smaller, rather stylistic, comments. Digging deeper into the test cases and the implementation requires a bit more time.

**Comment by mildm8nnered** [comment]
> Sorry for the very late feedback! This is a quite complex topic which scares me off a little. 😅
> 
> I have some smaller, rather stylistic, comments. Digging deeper into the test cases and the implementation requires a bit more time.
> 
> Thank you for your patience! 🙏

No worries. I've been busy and on vacation as well.

This is quite fiddly stuff, but in this case, it's just about warnings, rather than behaviour. I tried to over-compensate in the test cases as much as possible.

File: Source/SwiftLintCore/Models/Issue.swift [hunk 17]
```diff
@@ -20,6 +20,22 @@ public enum Issue: LocalizedError, Equatable {
     /// Used rule IDs are invalid.
     case invalidRuleIDs(Set<String>)
 
+    /// Found a rule configuration for a rule that is not present in `only_rules`.
+    case configurationForRuleNotPresentInOnlyRules(ruleID: String)
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Models/Issue.swift:24]: Any reason this uses a different naming style?
```suggestion
    case ruleNotPresentInOnlyRules(ruleID: String)
```

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift [hunk 18]
```diff
@@ -411,12 +411,159 @@ extension ConfigurationTests {
...
+        let optInRuleType = ImplicitReturnRule.self
+        XCTAssertTrue((optInRuleType as Any) is any OptInRule.Type)
+        testOnlyConfigurationDisabledRulesWarnings(ruleType: optInRuleType)
+
+        let defaultRuleType = BlockBasedKVORule.self
+        XCTAssertFalse((defaultRuleType as Any) is any OptInRule.Type)
+        testOnlyConfigurationDisabledRulesWarnings(ruleType: defaultRuleType)
+    }
+
+    private func testOnlyConfigurationDisabledRulesWarnings(ruleType: any Rule.Type) {
```
Comment (SimplyDanny) [inline Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift:544]: I suggest to inline this method and unroll all the test cases. The lists and loops make these rather simple cases harder to follow.

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift [hunk 19]
```diff
@@ -411,12 +411,159 @@ extension ConfigurationTests {
...
+
+        let configurations = [
+            Configuration(rulesMode: .default(disabled: [], optIn: [])),
+            Configuration(rulesMode: .default(disabled: [], optIn: [ruleIdentifier])),
+            Configuration(rulesMode: .default(disabled: [ruleIdentifier], optIn: [ruleIdentifier])),
+            Configuration(rulesMode: .default(disabled: [ruleIdentifier], optIn: []))
+        ]
+
+        for parentConfiguration in parentConfigurations {
+            testParentConfiguration(parentConfiguration, configurations: configurations, ruleType: ruleType)
```
Comment (SimplyDanny) [inline Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift:453]: Move the loop over `configurations` here to indicate that all combinations are checked here.

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift [hunk 20]
```diff
@@ -411,12 +411,159 @@ extension ConfigurationTests {
...
+                let mergedConfiguration = parentConfiguration?.merged(withChild: configuration) ?? configuration
+                let isEnabled = mergedConfiguration.contains(rule: ruleType)
+                let issue = validateConfiguredRuleIsEnabled(
+                    parentConfiguration: parentConfiguration,
+                    disabledRules: disabledRules,
+                    optInRules: optInRules,
+                    ruleType: ruleType
+                )
+                XCTAssertEqual(isEnabled, issue == nil)
+                if let issue {
```
Comment (SimplyDanny) [inline Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift:505]: Unwrapping shouldn't be needed if `issues` is exclusively used for comparisons in assertions. Leads to one less indentation ...

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift [hunk 21]
```diff
@@ -411,12 +411,159 @@ extension ConfigurationTests {
...
+            Configuration(rulesMode: .default(disabled: [ruleIdentifier], optIn: [ruleIdentifier])),
+            Configuration(rulesMode: .default(disabled: [ruleIdentifier], optIn: []))
+        ]
+
+        for parentConfiguration in parentConfigurations {
+            testParentConfiguration(parentConfiguration, configurations: configurations, ruleType: ruleType)
+        }
+    }
+
+    private func validateConfiguredRuleIsEnabled(
```
Comment (SimplyDanny) [inline Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift:457]: This part looks like a reimplementation of a part that's used in non-test code. Can we somehow reused it?

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift (hunk 18 above)
Comment (mildm8nnered) [reply Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift:513]: yep, much shorter now

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift (hunk 20 above)
Comment (mildm8nnered) [reply Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift]: So the code below does presume that `issue` is non-nil, but I've switched to a guard to reduce indentation

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift (hunk 21 above)
Comment (mildm8nnered) [reply Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift]: Yes, I managed to eliminate this with some refactoring

File: Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift [hunk 22]
```diff
@@ -411,12 +411,113 @@ extension ConfigurationTests {
...
+            guard let issue else {
+                return
+            }
+            let ruleIdentifier = ruleType.identifier
+            if disabledRules.isEmpty, optInRules.isEmpty {
+                if parentConfiguration == nil ||
+                    parentConfiguration == Configuration.emptyDefaultConfiguration() {
+                    XCTAssertEqual(issue, Issue.ruleNotEnabledInOptInRules(ruleID: ruleIdentifier))
+                    return
+                }
```
Comment (SimplyDanny) [inline Tests/SwiftLintFrameworkTests/ConfigurationTests+MultipleConfigs.swift:483]: `else if` to avoid the return.

File: Source/SwiftLintCore/Extensions/Configuration+Parsing.swift [hunk 23]
```diff
@@ -147,35 +152,115 @@ extension Configuration {
...
+        if case .only(let onlyRules) = parentConfiguration?.rulesMode {
+            enabledInParentRules = onlyRules
+        } else if case .default(let parentDisabledRules, let parentOptInRules) = parentConfiguration?.rulesMode {
+            enabledInParentRules = parentOptInRules
+            disabledInParentRules = parentDisabledRules
+        }
+        allEnabledRules = enabledInParentRules
+            .subtracting(disabledInParentRules)
+            .union(optInRules)
+            .subtracting(disabledRules)
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Extensions/Configuration+Parsing.swift:203]: What about rules enabled by default? Are they included somewhere else?

File: Source/SwiftLintCore/Extensions/Configuration+Parsing.swift [hunk 24]
```diff
@@ -147,35 +152,115 @@ extension Configuration {
...
+                return Issue.ruleDisabledInDisabledRules(ruleID: ruleType.identifier)
+            } else {
+                return nil
+            }
+        }
+
+        let allIdentifiers = ruleType.description.allIdentifiers
+
+        if allEnabledRules.isDisjoint(with: allIdentifiers) {
+            if disabledRules.isDisjoint(with: allIdentifiers) == false {
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Extensions/Configuration+Parsing.swift:247]:
```suggestion
            if !disabledRules.isDisjoint(with: allIdentifiers) {
```

File: Source/SwiftLintCore/Extensions/Configuration+Parsing.swift [hunk 25]
```diff
@@ -147,35 +152,115 @@ extension Configuration {
...
+                return Issue.ruleDisabledInDisabledRules(ruleID: ruleType.identifier)
+            } else if disabledInParentRules.isDisjoint(with: allIdentifiers) == false {
```
Comment (SimplyDanny) [inline Source/SwiftLintCore/Extensions/Configuration+Parsing.swift:249]:
```suggestion
            } else if !disabledInParentRules.isDisjoint(with: allIdentifiers) {
```

**Review by SimplyDanny — CHANGES_REQUESTED** [review]
Looks a lot easier now!

I still have some stylistic remarks and a question.

**Comment by mildm8nnered** [comment]
Dam - just noticed this is failing CI - will take a look later on.

**Comment by SimplyDanny** [comment]
General review and CI are good now. 👍 However, there are still a few unresolved review comments.

**Comment by mildm8nnered** [comment]
> General review and CI are good now. 👍 However, there are still a few unresolved review comments.

Cool - I will take a look at those.

File: Source/SwiftLintCore/Extensions/Configuration+Parsing.swift (hunk 23 above)
Comment (mildm8nnered) [reply Source/SwiftLintCore/Extensions/Configuration+Parsing.swift:203]: That is a good point. I *think* they're covered, but there may be some cases I haven't thought of.

Comment (mildm8nnered) [reply Source/SwiftLintCore/Extensions/Configuration+Parsing.swift:203]: Yep, they should work ok, and there are test cases for them.

If a rule is not present in `allEnabledRules`, then we will look to see if it is disabled in the parent or child. If not, and it's a default rule, then we only report an issue if the configuration uses only rules, and our rule is not present there.

**Comment by mildm8nnered** [comment]
> > General review and CI are good now. 👍 However, there are still a few unresolved review comments.
> 
> Cool - I will take a look at those.

ok - I think I've responded to everything, but if I've missed anything let me know!

**Review by SimplyDanny — APPROVED** [review]
This has been a tough topic! After almost one year after this got opened, it will finally be merged. 😅

Thank you so much for your patience and the continuous improvements and rework!

**Comment by mildm8nnered** [comment]
> Wow ... this has been a tough topic! After almost one year after this got opened, it will finally be merged. 😅
> 
> Thank you so much for your patience and the continuous improvements and rework!

No problem. We got there in the end :-)
