### PR TITLE
Fix a false positive in `unused_closure_parameter` rule

### LINKED ISSUE #2062: Invalid trigger for unused_closure_parameter when parameter is used in string interpolation
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
~> swiftlint lint
Loading configuration from '.swiftlint.yml'
Linting Swift files in current working directory
# ... non problematic files
/.../Mapper.swift:53:31: warning: Unused Closure Parameter Violation: Unused parameter "input" in a closure should be replaced with _. (unused_closure_parameter)
/.../Mapper.swift:53:38: warning: Unused Closure Parameter Violation: Unused parameter "context" in a closure should be replaced with _. (unused_closure_parameter)
/.../Mapper.swift:53:47: warning: Unused Closure Parameter Violation: Unused parameter "output" in a closure should be replaced with _. (unused_closure_parameter)
Done linting! Found 3 violations, 0 serious in 37 files.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
```bash
~> swiftlint version
0.25.0
````
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
`Homebrew`
* Paste your configuration file:

```yml
included:
  - Sources

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - extension_access_modifier
  - explicit_enum_raw_value
  - void_return
  - explicit_type_interface
  - number_separator
  - trailing_whitespace
  - function_body_length
  - line_length
  - redundant_optional_initialization
  - explicit_top_level_acl
  - identifier_name
  - no_grouping_extension

nesting:
  type_level: 2

colon:
  apply_to_dictionaries: false

statement_position:
  statement_mode: uncuddled_else
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.

No

* Which Xcode version are you using (check `xcode-select -p`)?
```bash
~> xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

As the title state, the rule doesn't appear to see the variables referenced via string interpolation in the scope of this function.
screen shot 2018-02-23 at 5 24 52 pm
screen shot 2018-02-23 at 5 25 02 pm

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #2062

This will probably have some performance impact, but correctness should be a priority.

### CODE REVIEW

File: Source/SwiftLintFramework/Extensions/SyntaxMap+SwiftLint.swift [hunk 1]
```diff
@@ -12,18 +12,11 @@ extension SyntaxMap {
...
-
         guard let startIndex = tokens.index(where: intersect) else {
             return []
         }
         let tokensBeginningIntersect = tokens.lazy.suffix(from: startIndex)
-        if let endIndex = tokensBeginningIntersect.index(where: notIntersect) {
-            return Array(tokensBeginningIntersect.prefix(upTo: endIndex))
-        }
-        return Array(tokensBeginningIntersect)
+        return Array(tokensBeginningIntersect.filter(intersect))
```
Comment (marcelofabri) [inline Source/SwiftLintFramework/Extensions/SyntaxMap+SwiftLint.swift]: I had to change this because it's not guaranteed that the first token that doesn't intersect the range is the last one that does. For example:

```json
[
  {
    "length" : 10,
    "offset" : 50,
    "type" : "source.lang.swift.syntaxtype.string"
  },
  {
    "length" : 1,
    "offset" : 52,
    "type" : "source.lang.swift.syntaxtype.string_interpolation_anchor"
  },
  {
    "length" : 5,
    "offset" : 53,
    "type" : "source.lang.swift.syntaxtype.identifier"
  },
  {
    "length" : 1,
    "offset" : 58,
    "type" : "source.lang.swift.syntaxtype.string_interpolation_anchor"
  },
  {
    "length" : 1,
    "offset" : 59,
    "type" : "source.lang.swift.syntaxtype.string"
  }
]
```

Searching by (53, 5) would return only the first token, because the second one isn't in the range. However, the 3rd one is and should be included in the result.

**Comment by marcelofabri** [comment]
I didn't see that much difference when running oss-check locally:

```
Message: Linting Aerial with this PR took 0.28s vs 0.28s on master (0% slower)
Message: Linting Alamofire with this PR took 2.14s vs 2.13s on master (0% slower)
Message: Linting Firefox with this PR took 8.0s vs 7.96s on master (0% slower)
Message: Linting Kickstarter with this PR took 10.65s vs 10.56s on master (0% slower)
Message: Linting Moya with this PR took 1.13s vs 1.15s on master (1% faster)
Message: Linting Nimble with this PR took 0.96s vs 0.94s on master (2% slower)
Message: Linting Quick with this PR took 0.31s vs 0.3s on master (3% slower)
Message: Linting Realm with this PR took 2.12s vs 2.1s on master (0% slower)
Message: Linting SourceKitten with this PR took 0.7s vs 0.68s on master (2% slower)
Message: Linting Sourcery with this PR took 2.95s vs 2.97s on master (0% faster)
Message: Linting Swift with this PR took 19.91s vs 19.67s on master (1% slower)
Message: Linting WordPress with this PR took 9.48s vs 9.39s on master (0% slower)
```
