### PR TITLE
Fixes false positives on `explicit_type_interface` with type reference assignments

### LINKED ISSUE #2636: False positive in rule explicit_type_interface with allowRedundancy
For this code

```swift
private let l10n = L10n.Communication.self
```

using this configuration

```yaml
explicit_type_interface:
  allow_redundancy: true
  excluded:
    - local
```

there shouldn't be any warnings, but there is.

Rationale: The usage of this rule here is mostly for improving readability, not performance of the compiler. We also try to prevent redundant type annotations, why explicitly writing the type here wouldn't be right. Thus this rules behavior must be changed.

### PR DESCRIPTION
**Pull request by Dschee**
Fixes #2636.

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/Idiomatic/ExplicitTypeInterfaceRule.swift [hunk 1]
```diff
@@ -130,6 +132,23 @@ private extension Dictionary where Key == String, Value == SourceKitRepresentabl
...
+            let nameLength = nameLength,
+            case let contents = file.contents.bridge(),
+            let afterNameRange = contents.byteRangeToNSRange(start: nameOffset + nameLength, length: 0)
+        else {
+            return false
+        }
+
+        let contentAfterName = contents.substring(from: afterNameRange.location)
+        let typeAssignment =
+            regex("^\\s*=\\s*(?:try[!?]?\\s+)?\\[?\\p{Lu}[^\\(\\s<]*(?:<[^\\>]*>)?(?::\\s*[^\\(\\n]+)?\\]?self")
```
Comment (marcelofabri) [inline Source/SwiftLintFramework/Rules/Idiomatic/ExplicitTypeInterfaceRule.swift]: Can this be simplified? 😲
For example, we don't need to worry about `try` in this case.

Also, shouldn't it enforce a `.` before `self`?

Comment (Dschee) [reply Source/SwiftLintFramework/Rules/Idiomatic/ExplicitTypeInterfaceRule.swift]: I simplified it and made sure there's a `.` before the `self`.
