### PR TITLE
fix infinite regex search & 'where' false positive in ConditionalBindingCascadeRule

### LINKED ISSUE #340: `ConditionalBindingCascadeRule` hangs up on linting KeychainAccess
It can be reproduced by
`curl https://raw.githubusercontent.com/kishikawakatsumi/KeychainAccess/master/Examples/Playground-iOS.playground/section-1.swift |swiftlint lint --use-stdin`

### PR DESCRIPTION
**Pull request by jpsim**
Fixes #340 and #347 /cc @norio-nomura

### CODE REVIEW

**Comment by jpsim** [comment]
A small performance win too!

* `testSwiftLintLints` in master: 2.246 seconds
* `testSwiftLintLints` in this branch: 2.061 seconds

File: Source/SwiftLintFramework/Rules/ConditionalBindingCascadeRule.swift [hunk 1]
```diff
@@ -36,12 +37,10 @@ public struct ConditionalBindingCascadeRule: Rule {
...
     public func validateFile(file: File) -> [StyleViolation] {
-        let conditionalBindingKeywords = ["if", "guard"]
-        let pattern =  "^(" +
-                        conditionalBindingKeywords.joinWithSeparator("|") +
-                        ")(\\s*?)let((.|\\s)*?),(\\s*?)let((.|\\s)*?)\\{"
-        return file.matchPattern(pattern,
-            excludingSyntaxKinds: SyntaxKind.commentAndStringKinds()).map {
+        return file.matchPattern("^(if|guard)(.*?)let(.*?),(.*?)let(.*?)\\{",
+            excludingSyntaxKinds: SyntaxKind.commentAndStringKinds()).filter {
+                !(file.contents as NSString).substringWithRange($0).containsString("where")
```
Comment (jpsim) [inline Source/SwiftLintFramework/Rules/ConditionalBindingCascadeRule.swift]: I'm sure this could lead to some missed violations, but I'm not too concerned with that right now.

**Comment by jpsim** [comment]
Merging because it addresses a critical issue. @norio-nomura please let me know if you can think of a better way to handle `where` cases.

**Comment by norio-nomura** [comment]
That's enough now! :+1:
