### PR TITLE
Inline test failure messages

### LINKED ISSUE #3035: Improve tests with inline failure messages
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When developing rules and fixing bugs, trying to correlate the test output with the code can be difficult. It would be nicer if incorrectly triggered or ignored examples were highlighted in Xcode like other test failures.

This would be possible with the technique I describe in this blog post: [XCTest Line by Line](https://www.rightpoint.com/rplabs/2019/03/xctest-line-by-line/)

As a quick sketch, it would transform the test case declarations from this:

```swift
public static let description = RuleDescription(
    identifier: "foo",
    name: "Foo",
    description: "some description",
    kind: .idiomatic,
    minSwiftVersion: .fourDotOne,
    nonTriggeringExamples: [
        """
        enum SomeExample { }
        """, // etc
```

to something more like this:

```swift
public static let description = RuleDescription(
    identifier: "foo",
    name: "Foo",
    description: "some description",
    kind: .idiomatic,
    minSwiftVersion: .fourDotOne,
    nonTriggeringExamples: [
        Example("""
        enum SomeExample {}
        """), // etc etc
```

The addition of the `Example` wrapper struct would capture the file and line number, which would be passed to the `XCTest` methods, ensuring that failures are reflected on the correct line. The initializer of the `Example` struct would have to look like this:

```swift
// "example" parameter could also be a StaticString if you want to encourage
// passing string literals to aid in debugging
init(_ example: String, file: StaticString = #file, line: Uint = #line)
```

I'd be interested in contributing a PR to address this.

### PR DESCRIPTION
**Pull request by ZevEisenberg**
Fixes #3035 

- [x] Make it work.
- [x] Finish adding `Example` literal init to all strings and remove `ExpressibleByStringLiteral` conformance from `Example` type.
- [x] Find out whether we can remove trailing `\n` from the many test cases that have them.
- [x] ~Remove trailing newlines from all examples where possible.~ rolled back because it was too invasive
- [x] Resolve file and line length warnings.
- [x] fix broken tests
- [x] ~merge https://github.com/ZevEisenberg/SwiftLint/pull/1~ this PR is no longer dependent on that one

@jpsim here's a start! I took a pretty lazy approach to converting files over to the new format, opting for an `ExpressibleByStringLiteral` band-aid (that [doesn't even partially work](https://bugs.swift.org/browse/SR-12034)) just so I can get it up and running. Before merging, we'll need to go through and add an explicit `Example(...)` initializer to literally every example.

I've also been pretty liberal with smashing things in order to get it all compiling, so I'm very open to ideas if you have suggestions for how to make the PR more conservative.

I have two open questions that I'd love some feedback on:

1. A ton of examples have a trailing `\n`, but not all of them do. Do you know why it's there? Can I delete those newlines? Here's an example: `"public func a() {}\n"`.
1. Some of the file and line length warnings don't seem that useful on a project like this, where file length isn't a good indicator of code complexity. it's just a bunch of "data"-like string literals, and sometimes the file gets longer just because we wrap lines to make them clearer. However, I'm not the project owner, so I'd appreciate any guidance you have on how to get around those warnings.

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
It's early days, but here's a proof of concept. It's aliiiiiive!
image

**Comment by jpsim** [comment]
Thanks for your work on this!

> 1. A ton of examples have a trailing `\n`, but not all of them do. Do you know why it's there? Can I delete those newlines? Here's an example: `"public func a() {}\n"`.

If I recall correctly, in the very early days all rules were run for every example, and one of the rules validated that files had a single newline at the end, so every example needed a newline to avoid triggering that rule. We now just run a single rule when validating each example, so these newlines are no longer required.

> 2\. Some of the file and line length warnings don't seem that useful on a project like this, where file length isn't a good indicator of code complexity. it's just a bunch of "data"-like string literals, and sometimes the file gets longer just because we wrap lines to make them clearer. However, I'm not the project owner, so I'd appreciate any guidance you have on how to get around those warnings.

This is why examples are often split into separate files than the rule implementations. I'd argue that having that kind of data-like string literals mixed in with the implementation ends up being noisy and hard to read, even if it doesn't contribute to the complexity of the code. At the end of the day, the linter is just there to help. If the best thing for the code quality is to disable the rule in some cases, that's perfectly valid.

---

Finally, there's another big migration happening right now touching a ton of files: #3037 
I just want to give you a heads up so you're not caught off guard if you invest time into this only to have many merge conflicts to then sort through.

**Comment by ZevEisenberg** [comment]
Thanks for the heads up on the other PR. Fortunately, they effectively merge cleanly right now (except for a file that I modified and you deleted; can I ask why some rule files were removed? Or is that temporary?).

**Comment by jpsim** [comment]
> can I ask why some rule files were removed? Or is that temporary?

That was temporary as we were migrating rules. That PR has merged now and it looks like there are no conflicts with this one!

File: Source/SwiftLintFramework/Models/Example.swift [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+
+    /// Returns a copy of the Example with all instances of the "↓" character removed.
+    func removingViolationMarkers() -> Example {
+        return with(code: code.replacingOccurrences(of: "↓", with: ""))
+    }
+}
+
+extension Example: Hashable {
+    public static func == (lhs: Example, rhs: Example) -> Bool {
+        // Ignoring file/line metadata beacuse two Examples could represent
```
Comment (jpsim) [inline Source/SwiftLintFramework/Models/Example.swift]: Typo
```suggestion
        // Ignoring file/line metadata because two Examples could represent
```

File: Source/SwiftLintFramework/Models/Example.swift [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+        // the same idea, but captured at two different points in the code
+        return lhs.code == rhs.code
+    }
+
+    public func hash(into hasher: inout Hasher) {
+        // Ignoring file/line metadata beacuse two Examples could represent
```
Comment (jpsim) [inline Source/SwiftLintFramework/Models/Example.swift]: Typo
```suggestion
        // Ignoring file/line metadata because two Examples could represent
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -10,7 +10,10 @@
 
 #### Enhancements
 
-* None.
+* Inline test failure messages to make development of SwiftLint easier. Test failures in triggering and non-triggering examples will appear inline in their respective files so you can immediately see which cases are working and which are not.
```
Comment (jpsim) [inline CHANGELOG.md]: Hard wrap at 80 characters please: https://github.com/realm/SwiftLint/blob/master/CONTRIBUTING.md#tracking-changes

File: CHANGELOG.md [hunk 4]
```diff
@@ -10,7 +10,10 @@
 
 #### Enhancements
 
-* None.
+* Inline test failure messages to make development of SwiftLint easier. Test failures in triggering and non-triggering examples will appear inline in their respective files so you can immediately see which cases are working and which are not.  
+  [ZevEisenberg](https://github.com/ZevEisenberg)
+  [#3040](https://github.com/realm/SwiftLint/pull/3040)
```
Comment (jpsim) [inline CHANGELOG.md]: Can just drop this line completely: https://github.com/realm/SwiftLint/blob/master/CONTRIBUTING.md#tracking-changes

File: Source/SwiftLintFramework/Documentation/RuleDocumentation.swift [hunk 5]
```diff
@@ -30,11 +30,11 @@ struct RuleDocumentation {
         var content = [h1(description.name), description.description, detailsSummary(ruleType.init())]
         if !description.nonTriggeringExamples.isEmpty {
             content += [h2("Non Triggering Examples")]
-            content += description.nonTriggeringExamples.map(formattedCode)
+            content += description.nonTriggeringExamples.map { $0.code }.map(formattedCode)
```
Comment (jpsim) [inline Source/SwiftLintFramework/Documentation/RuleDocumentation.swift]: Alternatively could make `formattedCode` take an `Example` as parameter.

File: Source/SwiftLintFramework/Models/Example.swift [hunk 6]
```diff
@@ -0,0 +1,71 @@
+/// Captures code and context information for an example of a triggering or
+/// non-triggering style
+public struct Example {
+    public var code: String
+
+    // file and line are optional because we need to conform to
+    // Codable, and StaticString isn't Codable, so we just ignore
```
Comment (jpsim) [inline Source/SwiftLintFramework/Models/Example.swift]: How do we use `Example`'s `Codable` conformance?

Comment (ZevEisenberg) [reply Source/SwiftLintFramework/Models/Example.swift]: It looked like `Codable` conformance of rules was strictly for reading and writing caches on disk, and that didn’t seem applicable when testing. Unfortunately, the file has to be stored as a `StaticString` in order to pass to XCTest stuff, which limits our options unless you want to entertain an investigation into unsafe bit casting.

**Comment by ZevEisenberg** [comment]
@jpsim thanks for the comments. I know it’s a bit of a monster, so I’m glad to know it’s not going into the void! Removing the new lines may have been too ambitious, because it seems to have broken a couple of newline-sensitive rules in unexpected ways that I’m having a hard time pinning down, so I may back off on that.

I’m having a little trouble closing the last 5% of work, and I’d love to pair with you or someone else who has a lot of experience with the code base to get it over the finish line. I’m free this weekend and all of next week, so the timing is good for me (which is why I’m doing it in the first place 😅).

File: Source/SwiftLintFramework/Models/Example.swift (hunk 6 above)
Comment (jpsim) [reply Source/SwiftLintFramework/Models/Example.swift]: Hmmm, I don’t think we should be encoding the examples for caching purposes. I don’t see why it’s being done that way now.

**Comment by jpsim** [comment]
I’m afraid I’m short on time these days but maybe you can find someone in the Slack group willing to help?

**Comment by ZevEisenberg** [comment]
I ended up removing the commits where I had deleted trailing new lines. Too much for one PR, and it was causing failures that I didn't want or need to deal with as part of this one.

File: CHANGELOG.md (hunk 4 above)
Comment (ZevEisenberg) [reply CHANGELOG.md]: I'm confused. That page says:
>4. A list of Markdown hyperlinks to the issues the change addresses. One entry per line. Usually just one. If there was no issue tracking this change, you may instead link to the change's pull request.
Many other changelog entries link to the issue or PR. Why drop this line?

File: Source/SwiftLintFramework/Models/Example.swift (hunk 6 above)
Comment (ZevEisenberg) [reply Source/SwiftLintFramework/Models/Example.swift]: The cascade goes Example → RuleDescription → StyleViolation → FileCacheEntry → FileCache and then all hell breaks loose 😓

Comment (ZevEisenberg) [reply Source/SwiftLintFramework/Models/Example.swift]: …but maybe it would be possible to store, not the full rule, but just the identifier, in the cache?

**Comment by ZevEisenberg** [comment]
I was surprised how much fell into place once I had removed the `\n`-deleting commits. Now there are just three file/function body length failures, and I'd love your input on whether it would best be in the spirit of the project to try to fix them, or to disable the linter.

Also, since this is now ready for review, please let me know if there's anything I can do to make your job easier for reviewing this. I know it's a lot, so if I can help by wrangling reviewers, I'm happy to do so.

**Comment by ZevEisenberg** [comment]
@jpsim in order to fix the length warnings, I ended up restructuring the test helpers. There are no material changes here - just moving files and functions around. I figured you'd want to review that stuff separately: https://github.com/ZevEisenberg/SwiftLint/pull/1

**Comment by PaulTaykalo** [comment]
@ZevEisenberg  please make sure that `swift test` is not failing on your machine
There are three errors ATM
```
/__w/1/s/Tests/SwiftLintFrameworkTests/TestHelpers.swift:455: error: IntegrationTests.testSwiftLintLints : failed - File should contain 400 lines or less: currently contains 455
/__w/1/s/Tests/SwiftLintFrameworkTests/TestHelpers.swift:164: error: IntegrationTests.testSwiftLintLints : failed - Function body should span 40 lines or less excluding comments and whitespace: currently spans 42 lines
/__w/1/s/Tests/SwiftLintFrameworkTests/TestHelpers.swift:370: error: IntegrationTests.testSwiftLintLints : failed - Function body should span 40 lines or less excluding comments and whitespace: currently spans 45 lines
```

**Comment by ZevEisenberg** [comment]
@PaulTaykalo thanks for taking a look. Fixing those failures involved a bunch of busywork that made this PR harder to review, so I fixed them on a sub-PR that I'd like to get reviewed and merged into this branch first. It's here, in case you've got time to look at it: https://github.com/ZevEisenberg/SwiftLint/pull/1

File: Source/SwiftLintFramework/Models/Example.swift (hunk 6 above)
Comment (ZevEisenberg) [reply Source/SwiftLintFramework/Models/Example.swift]: ☝🏻ended up doing that

**Comment by ZevEisenberg** [comment]
Many thanks to @PaulTaykalo for helping me figure out the best way to get this branch ready to merge. I'm deferring the test helper cleanup, which will be an independent PR.

File: Tests/SwiftLintFrameworkTests/TestHelpers.swift [hunk 7]
```diff
@@ -92,8 +94,9 @@ private extension Collection where Element == StyleViolation {
         return map { violation in
             let locationWithoutFile = Location(file: nil, line: violation.location.line,
                                                character: violation.location.character)
-            return StyleViolation(ruleDescription: violation.ruleDescription, severity: violation.severity,
-                                  location: locationWithoutFile, reason: violation.reason)
+            var new = violation
+            new.location = locationWithoutFile
```
Comment (PaulTaykalo) [inline Tests/SwiftLintFrameworkTests/TestHelpers.swift]: again we can use `with(location: locationWithoutFile`) extension
this will remove the need of having mutable property ad well as the  some rules disabing
https://github.com/realm/SwiftLint/pull/3040/files#diff-32f83ec6a61cedc75c20b4319015fff9R6

File: Source/SwiftLintFramework/Models/StyleViolation.swift [hunk 8]
```diff
@@ -1,13 +1,19 @@
...
     /// The description of the rule that generated this violation.
-    public let ruleDescription: RuleDescription
+    public let ruleDescription: String
+
+    /// The name of the rule that generated this violation.
+    public let ruleName: String
 
     /// The severity of this violation.
-    public let severity: ViolationSeverity
+    public var severity: ViolationSeverity
```
[the remark this answers is not in the document]
Comment (ZevEisenberg) [reply Source/SwiftLintFramework/Models/StyleViolation.swift]: Personal style: I'm fine making things `var` if I need to change them, and letting the call site's use of `let` or `var` determine the mutability. But I'm also happy to add `.with` modifiers to the `StyleViolation` type 🙂

**Comment by jpsim** [comment]
A big thank you @ZevEisenberg for pushing this through and @PaulTaykalo for the code review and shepherding this in! 👏 

Sorry I haven't been able to help much.
