### PR TITLE
fix: false positive on sorted_first_last with firstIndex(of:), firstIndex(where:), lastIndex(of:) and lastIndex(where:) method

### LINKED ISSUE #2700: False positive on SortedFirstLastRule (sorted_first_last) with firstIndex(of:), firstIndex(where:), lastIndex(of:) and lastIndex(where:)  method.
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`func index(of element: Element) -> AnyIndex?` method is deprecated in Xcode 10.2.
Its method should migrate to `func firstIndex(of element: Element) -> AnyIndex?`.
Since I migrated my code, SwiftLint warnings about SortedFirstLastRule.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ echo "keys.sorted().firstIndex(of: idx)" | swiftlint lint --no-cache --use-stdin --enable-all-rules
Loading configuration from '.swiftlint.yml'
<nopath>:1:1: warning: Min or Max over Sorted First or Last Violation: Prefer using `min()` or `max()` over `sorted().first` or `sorted().last` (sorted_first_last)
Done linting! Found 1 violation, 0 serious in 1 file.
```

And also `lastIndex(of:)`

```bash
$ echo "keys.sorted().lastIndex(of: idx)" | swiftlint lint --no-cache --use-stdin --enable-all-rules
Loading configuration from '.swiftlint.yml'
<nopath>:1:1: warning: Min or Max over Sorted First or Last Violation: Prefer using `min()` or `max()` over `sorted().first` or `sorted().last` (sorted_first_last)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.31.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
opt_in_rules:
  - sorted_first_last
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.

No

* Which Xcode version are you using (check `xcode-select -p`)? 10.2
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
keys.sorted().firstIndex(of: idx)
keys.sorted().lastIndex(of: idx)
```

### PR DESCRIPTION
**Pull request by r-plus**
Fixes #2700

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/Performance/SortedFirstLastRule.swift [hunk 1]
```diff
@@ -38,7 +38,7 @@ public struct SortedFirstLastRule: CallPairRule, OptInRule, ConfigurationProvide
 
     public func validate(file: File) -> [StyleViolation] {
         return validate(file: file,
-                        pattern: "[\\}\\)]\\s*\\.(first|last)",
+                        pattern: "[\\}\\)]\\s*\\.(first|last)(?!Index)",
```
Comment (marcelofabri) [inline Source/SwiftLintFramework/Rules/Performance/SortedFirstLastRule.swift]: can you add some non-triggering examples to make sure we don't break this in the future?

Comment (r-plus) [reply Source/SwiftLintFramework/Rules/Performance/SortedFirstLastRule.swift]: @marcelofabri thanks, I added some examples.

**Comment by marcelofabri** [comment]
Thanks! 💯
