### PR TITLE
Fix `indentation_width` false positives for multi-line conditions

### LINKED ISSUE #4961: indentation_width is not working well with multiple line if and guard
### New Issue Checklist

- [ ] Updated SwiftLint to the latest version
- [ ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

For example:
image

##### Complete output when running SwiftLint, including the stack trace and command used

Swift package plugin

### Environment

* SwiftLint version: 0.51.0
* Installation method used: SPM
* Paste your configuration file:

```yml
opt_in_rules:
  - indentation_width

indentation_width:
   severity: warning 
   indentation_width: 4
   include_comments: false
   include_compiler_directives: false
   trueinclude_multiline_strings: false
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
        guard let startSubvalue = subvalue(at: gesture.startLocation, minutes: minutes),
              let currentSubvalue = subvalue(at: gesture.location, minutes: minutes) else {
            return nil
        }
```

### PR DESCRIPTION
**Pull request by tanaev**
## Summary

- Fix false positives in `indentation_width` rule when `guard`/`if`/`while` conditions span multiple lines and are aligned to the keyword (e.g., `guard ` = 6 spaces), which is not a multiple of `indentation_width`
- Add a SwiftSyntax-based pre-pass (`MultilineConditionLineVisitor`) that collects continuation line numbers and skips them during indentation checks
- Add `include_multiline_conditions` configuration option (default: `false`) to control this behavior

Fixes #4961

## Test plan

- [x] Added `testIncludeMultilineConditions()` with cases for `guard`, `if`, `while`, nested conditions, and `include_multiline_conditions: true`
- [x] Added `nonTriggeringExamples` to rule description for multi-line `guard` and `if`
- [x] All existing `IndentationWidthRuleTests` pass (14 + 1 new = 15 tests, 0 failures)
- [x] Verify CI passes on all platforms

### CODE REVIEW

File: Tests/BuiltInRulesTests/IndentationWidthRuleTests.swift [hunk 1]
```diff
@@ -268,13 +268,40 @@ final class IndentationWidthRuleTests: SwiftLintTestCase {
...
+        let ifExample = """
+            if let x = foo(),
+               let y = bar() {
+                doSomething()
+            }
+            """
+
+        assertNoViolation(in: guardExample)
+        assertNoViolation(in: ifExample)
+        assertNoViolation(in: "while let x = foo(),\n      let y = bar() {\n    doSomething()\n}")
```
Comment (SimplyDanny) [inline Tests/BuiltInRulesTests/IndentationWidthRuleTests.swift:274]: Could you use a string block?

**Review by SimplyDanny — APPROVED** [review]
Looks good to me. Thanks!

Have you thought about not just ignoring conditions but linting against their proper indentation? For example:

```swift
if let a,
   let b {
    // ...
}
```
would be good, while
```swift
if let a,
    let b {
    // ...
}
```
wouldn't.

What about `guard` and its `else`? Should

```swift
guard let a
      else {
    return
}
```
trigger at the `else`. I guess not.

**Comment by tanaev** [comment]
> Looks good to me. Thanks!
> 
> Have you thought about not just ignoring conditions but linting against their proper indentation? For example:
> 
> ```swift
> if let a,
>    let b {
>     // ...
> }
> ```
> 
> would be good, while
> 
> ```swift
> if let a,
>     let b {
>     // ...
> }
> ```
> 
> wouldn't.
> 
> What about `guard` and its `else`? Should
> 
> ```swift
> guard let a
>       else {
>     return
> }
> ```
> 
> trigger at the `else`. I guess not.

Thanks. updated

File: CHANGELOG.md [hunk 2]
```diff
@@ -99,6 +99,13 @@
   in build tool plugins.  
   [SimplyDanny](https://github.com/SimplyDanny)
   [#6080](https://github.com/realm/SwiftLint/issues/6080)
+* Fix false positives in `indentation_width` rule for continuation lines
+  of multi-line `guard`/`if`/`while` conditions. A new option
+  `include_multiline_conditions` (default: `false`) skips these lines by
+  default. When enabled, it validates that continuation lines are aligned
+  with the first condition after the keyword.
+  [tanaev](https://github.com/tanaev)
+  [#4961](https://github.com/realm/SwiftLint/issues/4961)
```
Comment (SimplyDanny) [inline CHANGELOG.md:117]: Please append two spaces to the end of the description. They are required to enforce a line break in the rendered Markdown.

```suggestion

* Fix false positives in `indentation_width` rule for continuation lines
  of multi-line `guard`/`if`/`while` conditions. A new option
  `include_multiline_conditions` (default: `false`) skips these lines by
  default. When enabled, it validates that continuation lines are aligned
  with the first condition after the keyword.  
  [tanaev](https://github.com/tanaev)
  [#4961](https://github.com/realm/SwiftLint/issues/4961)
```

File: Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift [hunk 3]
```diff
@@ -42,105 +68,142 @@ struct IndentationWidthRule: OptInRule {
...
+    }
+
+    private func checkMultilineConditionAlignment(
+        line: Line, expectedColumn: Int, indentationCharacterCount: Int, file: SwiftLintFile
+    ) -> StyleViolation? {
+        if !configuration.includeMultilineConditions { return nil }
+        let prefix = String(line.content.prefix(indentationCharacterCount))
+        let spaceCount = prefix.filter { $0 == " " }.count
+        let tabCount = prefix.filter { $0 == "\t" }.count
+        let actualColumn = spaceCount + tabCount * configuration.indentationWidth
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift]: Can `actualColumn` be computed once for `indentationCharacterCount`. Perhaps it should be an object that can return tab count, space count and the combined count to be useable in other places, too.

File: Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift [hunk 4]
```diff
@@ -42,105 +68,142 @@ struct IndentationWidthRule: OptInRule {
...
+    }
+
+    private func parseIndentation(
+        line: Line, indentationCharacterCount: Int, file: SwiftLintFile
+    ) -> (Indentation, StyleViolation?) {
+        let prefix = String(line.content.prefix(indentationCharacterCount))
+        let tabCount = prefix.filter { $0 == "\t" }.count
+        let spaceCount = prefix.filter { $0 == " " }.count
+        if tabCount != 0, spaceCount != 0 {
+            let violation = StyleViolation(
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift]: Should this be `makeViolation`?

File: Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift [hunk 5]
```diff
@@ -42,105 +68,142 @@ struct IndentationWidthRule: OptInRule {
...
+    ) -> StyleViolation? {
+        let isValid = previousLineIndentations.contains { validate(indentation: indentation, comparingTo: $0) }
+        guard !isValid else { return nil }
+        let isIndentation = previousLineIndentations.last.map {
+            indentation.spacesEquivalent(indentationWidth: configuration.indentationWidth) >=
+                $0.spacesEquivalent(indentationWidth: configuration.indentationWidth)
+        } ?? true
+        let indentWidth = configuration.indentationWidth
+        return makeViolation(
+            file: file, line: line,
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift]:
```suggestion
            file: file, 
            line: line,
```

File: Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift [hunk 6]
```diff
@@ -42,105 +68,142 @@ struct IndentationWidthRule: OptInRule {
...
+    private func checkMultilineConditionAlignment(
+        line: Line, expectedColumn: Int, indentationCharacterCount: Int, file: SwiftLintFile
+    ) -> StyleViolation? {
+        if !configuration.includeMultilineConditions { return nil }
+        let prefix = String(line.content.prefix(indentationCharacterCount))
+        let spaceCount = prefix.filter { $0 == " " }.count
+        let tabCount = prefix.filter { $0 == "\t" }.count
+        let actualColumn = spaceCount + tabCount * configuration.indentationWidth
+        guard actualColumn != expectedColumn else { return nil }
+        return StyleViolation(
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift]: `makeViolation`?

File: Tests/BuiltInRulesTests/IndentationWidthRuleTests.swift [hunk 7]
```diff
@@ -268,13 +268,47 @@ final class IndentationWidthRuleTests: SwiftLintTestCase {
...
+        assertNoViolation(in: "if let x = foo(),\n        let y = bar() {\n    doSomething()\n}")
+    }
+
+    func testMultilineConditionsAlignmentChecked() {
+        // Properly aligned — no violations
+        let guardAligned = "guard let x = foo(),\n      let y = bar() else {\n    return\n}"
+        let ifAligned = "if let x = foo(),\n   let y = bar() {\n    doSomething()\n}"
+        let whileAligned = "while let x = foo(),\n      let y = bar() {\n    doSomething()\n}"
+        let guardNextLine = "guard\n    let x = foo(),\n    let y = bar()\nelse {\n    return\n}"
+        let ifThreeAligned = "if let a = foo(),\n   let b = bar(),\n   let c = baz() {\n    doSomething()\n}"
```
Comment (SimplyDanny) [inline Tests/BuiltInRulesTests/IndentationWidthRuleTests.swift:286]: String blocks would be much easier to read. But fine to keep it as is for now.

**Review by SimplyDanny — CHANGES_REQUESTED** [review]

File: Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift (hunk 6 above)
Comment (tanaev) [reply Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift]: [47d2fd2](https://github.com/realm/SwiftLint/pull/6505/commits/47d2fd29a965adcc50cde3b011c9837a5966006d)

File: Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift (hunk 4 above)
Comment (tanaev) [reply Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift]: [47d2fd2](https://github.com/realm/SwiftLint/pull/6505/commits/47d2fd29a965adcc50cde3b011c9837a5966006d)

File: Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift (hunk 3 above)
Comment (tanaev) [reply Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift]: [47d2fd2](https://github.com/realm/SwiftLint/pull/6505/commits/47d2fd29a965adcc50cde3b011c9837a5966006d)

**Review by SimplyDanny — APPROVED** [review]

File: Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift [hunk 8]
```diff
@@ -42,105 +90,134 @@ struct IndentationWidthRule: OptInRule {
...
+    ) -> StyleViolation? {
+        let isValid = previousLineIndentations.contains { validate(indentation: indentation, comparingTo: $0) }
+        guard !isValid else { return nil }
+        let isIndentation = previousLineIndentations.last.map {
+            indentation.spacesEquivalent(indentationWidth: configuration.indentationWidth) >=
+                $0.spacesEquivalent(indentationWidth: configuration.indentationWidth)
+        } ?? true
+        let indentWidth = configuration.indentationWidth
+        return makeViolation(
+            file: file,
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Style/IndentationWidthRule.swift]:
```suggestion
            file: file,
```
