### PR TITLE
Fix false positives on rule `unused_closure_parameter` with `self` arguments

### LINKED ISSUE #2437: False positive on unused_closure_parameter rule with self
Using SwiftLint 0.27.0 I get the following false positive:

```swift
// setup view model bindings
viewModel?.profileImage.didSet(weak: self) { (self, profileImage) in // << `self` in a closure should be replaced with _
    if let profileImage = profileImage {
        self.profileImageView.image = profileImage
    }
    else {
        self.profileImageView.image = UIImage(named: "avatar_100pt")
    }
}
```

The underlying implementation looks like this:
```
import Foundation

/// A binding wrapper to track changes on constant properties.
class ObservableProperty<ValueType> {
    // MARK: - Stored Instance Properties
    private var didSetClosures: [(ValueType) -> Void] = []

    private(set) var value: ValueType {
        didSet {
            didSetClosures.forEach { $0(value) }
        }
    }

    // MARK: - Initializers
    init(_ value: ValueType) {
        self.value = value
    }

    // MARK: - Instance Methods
    /// Will be called after the wrapped value is changed.
    /// `$0` is the passed parameter (usually `self`), `$1` is the new value.
    func didSet<WeakObject: AnyObject>(weak object: WeakObject, _ closure: @escaping (WeakObject, ValueType) -> Void) {
        let weakClosure: (ValueType) -> Void = { [weak object] value in
            guard let object = object else { return }
            closure(object, value)
        }

        didSetClosures.append(weakClosure)
        weakClosure(value)
    }

    /// Use to change the value wrapped as a variable.
    func set(_ newValue: ValueType) {
        value = newValue
    }
}
```

This is an implementation of the idea also implemented in https://github.com/dreymonde/Delegated and should therefore be warning-free. My best guess is that there's some kind of exception logic going on in the rule logic for `self` references.

### PR DESCRIPTION
**Pull request by Dschee**
Fixes #2437.

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/Lint/UnusedClosureParameterRule.swift [hunk 1]
```diff
@@ -150,7 +160,7 @@ public struct UnusedClosureParameterRule: SubstitutionCorrectableASTRule, Config
                 }
 
                 let token = tokens.first(where: { token -> Bool in
-                    return SyntaxKind(rawValue: token.type) == .identifier &&
+                    return (SyntaxKind(rawValue: token.type) == .identifier || name == "self") &&
```
Comment (marcelofabri) [inline Source/SwiftLintFramework/Rules/Lint/UnusedClosureParameterRule.swift]: you should check if `SyntaxKind(rawValue: token.type) == .keyword` in this case to avoid any potential issues

Comment (Dschee) [reply Source/SwiftLintFramework/Rules/Lint/UnusedClosureParameterRule.swift]: Done.

**Comment by marcelofabri** [comment]
@Dschee feel free to merge this after the conflict is resolved
