### PR TITLE
Exclude `self.x = x` from being reported in the `redundant_self_in_closure` rule

### LINKED ISSUE #4988: `redundant_self_in_closure` rule can behave unexpectedly with `withAnimation(_:_:)`
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

1. Run SwiftLint v0.52.0 to the following code, for example
```swift
import SwiftUI

struct SampleView: View {
    @State private var number = 0

    var body: some View {
        Text("Sample")
    }

    private func add(_ number: Int) {
        withAnimation {
            self.number = number
        }
    }
}
```

2. SwiftLint removed `self` and we have an error like ↓
スクリーンショット 2023-05-11 13 57 25

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint --enable-all-rules --fix
Correcting Swift files in current working directory
Correcting 'Contents.swift' (1/1)
/Users/sakai.yunosuke/test/Contents.swift:12:13 Corrected Redundant Self in Closure
Done correcting 1 file!
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?: 0.52.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?: Homebrew
* Paste your configuration file: No configuration file
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?: No
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?: Xcode 14.3
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.
  * I have an example in "Describe the bug" section above.

### PR DESCRIPTION
**Pull request by SimplyDanny**
Fixes #4988.

### CODE REVIEW

File: Source/SwiftLintBuiltInRules/Rules/Style/RedundantSelfInClosureRule.swift [hunk 1]
```diff
@@ -287,8 +296,20 @@ private class ExplicitSelfVisitor: ViolationsSyntaxVisitor {
         super.init(viewMode: .sourceAccurate)
     }
 
+    override func visit(_ node: SequenceExprSyntax) -> SyntaxVisitorContinueKind {
+        let elements = node.elements
+        if elements.count == 3,
+           let assignee = elements.first?.as(MemberAccessExprSyntax.self), assignee.isBaseSelf,
+           elements.dropFirst(1).first?.is(AssignmentExprSyntax.self) == true,
+           elements.dropFirst(2).first?.as(IdentifierExprSyntax.self)?.identifier.text == assignee.name.text {
+            // We have something like `self.x = x` which is quite common and should thus be skipped.
```
Comment (jpsim) [inline Source/SwiftLintBuiltInRules/Rules/Style/RedundantSelfInClosureRule.swift:305]: Clever!
