### PR TITLE
Detect parameter attribute in vertical_parameter_alignment

### LINKED ISSUE #2792: vertical_parameter_alignment is triggered for @ViewBuilder
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`vertical_parameter_alignment` rule is triggered for this case:

```swift
    init(data: Data,
         numberOfColumns: Int,
         spacing: Length,
         @ViewBuilder content: @escaping (Data.Element.IdentifiedValue) -> Content) {
        self.grid = Grid(items: data, numberOfColumns: numberOfColumns)
        self.spacing = spacing
        self.content = content
    }
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.33.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
downloaded package file from github

```swift
// This triggers a violation:
    init(data: Data,
         numberOfColumns: Int,
         spacing: Length,
         @ViewBuilder content: @escaping (Data.Element.IdentifiedValue) -> Content) {
        self.grid = Grid(items: data, numberOfColumns: numberOfColumns)
        self.spacing = spacing
        self.content = content
    }
```

Can perform PR if agreed

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #2792

### CODE REVIEW

File: Source/SwiftLintFramework/Models/SwiftVersion.swift [hunk 1]
```diff
@@ -38,6 +39,13 @@ public extension SwiftVersion {
             }
         }
 
+        if !Request.disableSourceKit,
+            case let opaqueReturnFile = File(contents: "func a() -> some A {}"),
+            case let expectedKinds: [SyntaxKind] = [.keyword, .identifier, .keyword, .typeidentifier],
+            opaqueReturnFile.syntaxMap.tokens.compactMap({ SyntaxKind(rawValue: $0.type) }) == expectedKinds {
```
Comment (marcelofabri) [inline Source/SwiftLintFramework/Models/SwiftVersion.swift]: this should eventually be the replaced with the [the new SourceKit request](https://github.com/apple/swift/pull/22010)

Comment (marcelofabri) [reply Source/SwiftLintFramework/Models/SwiftVersion.swift]: Done in 0652b32

**Comment by jpsim** [comment]
Nice 👌
