### PR TITLE
Fix "superfluous_disable_command" / "disable all" interference

### LINKED ISSUE #2670: `superfluous_disable_command` overrides `disable all`
With the following code...

```
// swiftlint:disable all
// swiftlint:disable some_rule
```

... where `some_rule` isn't violated in the context that follows, I get a `superfluous_disable_command` warning. This is probably not intentional, as the purpose of `swiftlint:disable all` is to silence every possible warning, including `superfluous_disable_command` warnings.

If my guess that this is a bug is right, I'd be happy to push a fix.

### Environment

* SwiftLint 0.31.0 (Installed via Homebrew)
* Xcode 10.1

### PR DESCRIPTION
**Pull request by fredpi**
Closes #2670.

### CODE REVIEW

File: Tests/SwiftLintFrameworkTests/CommandTests.swift [hunk 1]
```diff
@@ -223,6 +225,37 @@ class CommandTests: XCTestCase {
         )
     }
 
+    func testDisableAllOverridesSuperfluousDisableCommand() {
+        XCTAssert(
+            !violations(
+                "//swiftlint:disable all\n// swiftlint:disable nesting\nprint(123)\n"
+            ).contains {
+                $0.ruleDescription.identifier == "superfluous_disable_command"
```
Comment (marcelofabri) [inline Tests/SwiftLintFrameworkTests/CommandTests.swift]: nitpick: can you check `.isEmpty` instead? This could potentially catch other issues

**Comment by marcelofabri** [comment]
@fredpi Thanks for the quick update, will merge it once it's green ✅

**Comment by jpsim** [comment]
💯
