### PR TITLE
Fix false positive on shorthand_operator rule

### LINKED ISSUE #1156: Inappropriate shorthand operator violation
`self.flashModeSelectionView.alpha = 1.0 - self.flashModeSelectionView.alpha`.
I can't find an easy conversion for this. I think this should be out of the rule. I mean no check for it because it has a `-` before on the right side of the `=`.
Am I right?

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #1156

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/ShorthandOperatorRule.swift [hunk 1]
```diff
@@ -33,27 +33,37 @@ public struct ShorthandOperatorRule: ConfigurationProviderRule {
...
     )
 
-    private static let allOperators = ["+", "-", "/", "*"]
+    private static let allOperators = ["-", "/"] + commutativeOperators
+    private static let commutativeOperators = ["+", "*"]
 
     private static let pattern: String = {
-        let escapedOperators = allOperators.map { "\\\($0)" }.joined()
-        let operators = "[\(escapedOperators)]"
+        let escaped = { (operators: [String]) -> String in
```
Comment (aamctustwo) [inline Source/SwiftLintFramework/Rules/ShorthandOperatorRule.swift]: You use this pattern to escape characters in OperatorFunctionWhitespaceRule and OperatorUsageWhitespaceRule (and possibly others). Might be worth refactoring this into a helper?

Comment (marcelofabri) [inline Source/SwiftLintFramework/Rules/ShorthandOperatorRule.swift]: I don't think it's complex enough to justify the additional complexity
