### PR TITLE
Ignore `no_magic_numbers` violations if they are in an extension of a test class (only works in the same file)

### LINKED ISSUE #5137: extension of test class should NOT trigger no_magic_numbers rule
### New Issue Checklist

- [x ] Updated SwiftLint to the latest version
- [x ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
- If extend from a test class, the no_magic_rule should not apply to the extension.
- https://github.com/realm/SwiftLint/issues/4896 that no_magic_number rules should not apply to Tests, that only works within the test class but not extension of the test class.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint --path /Tests/LintTests/MyTests.swift  --no-cache --enable-all-rules
warning: The --path option is deprecated. Pass the path(s) to lint last to the swiftlint command.
Linting Swift files at paths Tests/LintTests/MyTests.swift
Linting 'MyTests.swift' (1/1)
warning: The `anyobject_protocol` rule is now deprecated and will be completely removed in a future release.
warning: The `inert_defer` rule is now deprecated and will be completely removed in a future release.
warning: The `unused_capture_list` rule is now deprecated and will be completely removed in a future release.
/Tests/LintTests/MyTests.swift:4:5: warning: Explicit ACL Violation: All declarations should specify Access Control Level keywords explicitly (explicit_acl)
/Tests/LintTests/MyTests.swift:5:13: warning: Explicit Type Interface Violation: Properties should have a type interface (explicit_type_interface)
/Tests/LintTests/MyTests.swift:12:13: warning: Explicit Type Interface Violation: Properties should have a type interface (explicit_type_interface)
/Tests/LintTests/MyTests.swift:11:5: warning: Missing Docs Violation: public declarations should be documented (missing_docs)
/Tests/LintTests/MyTests.swift:10:1: error: No Extension Access Modifier Violation: Prefer not to use extension access modifiers (no_extension_access_modifier)
/Tests/LintTests/MyTests.swift:10:8: warning: No Grouping Extension Violation: Extensions shouldn't be used to group code within the same source file (no_grouping_extension)

/Tests/LintTests/MyTests.swift:13:42: warning: No Magic Numbers Violation: Magic numbers should be replaced by named constants (no_magic_numbers)

/Tests/LintTests/MyTests.swift:6:9: warning: Prefer Nimble Violation: Prefer Nimble matchers over XCTAssert functions (prefer_nimble)
/Tests/LintTests/MyTests.swift:13:9: warning: Prefer Nimble Violation: Prefer Nimble matchers over XCTAssert functions (prefer_nimble)
/Tests/LintTests/MyTests.swift:3:14: warning: Required Deinit Violation: Classes should have an explicit deinit method (required_deinit)
Done linting! Found 10 violations, 1 serious in 1 file.
```

### Environment

* SwiftLint version: 0.52.4
* both homebrew and swiftcommandplugins: both use the same swiftlint version and can reproduce the bug
* Paste your configuration file:

```yml
opt_in_rules:
- no_magic_numbers
```
We use default settings so "XCTestCase" should by default ignored by no_magic_number rule

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
no
* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 14.3 Build version 14E222b
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
import XCTest

final class MyTests: XCTestCase {
    func testMagicNumberRuleNotApplied() {
        let collection = []
        XCTAssertEqual(collection.count, 2) 
    }
}

extension MyTests {
    func testMagicNumberRuleApplied() {
        let collection = []
        XCTAssertEqual(collection.count, 2) // This triggers a no-magic-rule violation:
    }
}
```

### PR DESCRIPTION
**Pull request by mildm8nnered**
Ignores violations if they are present in an extension, if that extension extends a child of the specified `testParentClasses`, as long as the class declaration is in the same source file.

Partially resolves #5137

This was harder that I thought, and also more useful than expected, given the number of violations this (apparently correctly) fixes in the OSS tests.

We now keep track of class declarations, and whether they inherit from `testParentClasses` or not.

When we see a violation in an extension, unless we already know that it extends a test class, we add it to the violations.

If later in the file, we see the class declaration, and it extends one of the `testParentClasses`, we remove the violations from the list.

This should work no matter where in the file the class declaration occurs.

### CODE REVIEW

File: Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift [hunk 1]
```diff
@@ -126,4 +209,15 @@ private extension ExprSyntaxProtocol {
         }
         return false
     }
+
+    func extendedClassName() -> String? {
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift:213]:
```suggestion
    func extendedTypeName() -> String? {
```

File: Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift [hunk 2]
```diff
@@ -76,23 +115,67 @@ struct NoMagicNumbersRule: SwiftSyntaxRule, OptInRule, ConfigurationProviderRule
...
         }
 
         override func visitPost(_ node: IntegerLiteralExprSyntax) {
-            if node.isMemberOfATestClass(testParentClasses) == false, node.digits.isMagicNumber {
-                violations.append(node.digits.positionAfterSkippingLeadingTrivia)
+            guard node.digits.isMagicNumber else {
+                return
+            }
+            let violation = node.digits.positionAfterSkippingLeadingTrivia
+            process(violation: violation, forNode: node)
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift:150]: `process` is not very descriptive. The position can be gathered from the node like `node.positionAfterSkippingLeadingTrivia`:
```suggestion
            collectViolations(forNode: node)
```

File: Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift [hunk 3]
```diff
@@ -76,23 +115,67 @@ struct NoMagicNumbersRule: SwiftSyntaxRule, OptInRule, ConfigurationProviderRule
...
+        }
+
+        private func process(violation: AbsolutePosition, forNode node: ExprSyntaxProtocol) {
+            guard !node.isMemberOfATestClass(testParentClasses) else {
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift:154]: Prefer to avoid the negation by using an `if` statement.

File: Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift [hunk 4]
```diff
@@ -76,23 +115,67 @@ struct NoMagicNumbersRule: SwiftSyntaxRule, OptInRule, ConfigurationProviderRule
...
+                return
+            }
+            if let extendedClassName = node.extendedClassName() {
+                if testClasses.contains(extendedClassName) == false {
+                    violations.append(violation)
+                    if nonTestClasses.contains(extendedClassName) == false {
+                        var possibleViolationsForClass = possibleViolations[extendedClassName] ?? []
+                        possibleViolationsForClass.append(violation)
+                        possibleViolations[extendedClassName] = possibleViolationsForClass
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift:163]:
```suggestion
                        possibleViolations[extendedClassName, default: []].append(violation)
```

File: Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift [hunk 5]
```diff
@@ -76,23 +115,67 @@ struct NoMagicNumbersRule: SwiftSyntaxRule, OptInRule, ConfigurationProviderRule
...
+            let violation = node.digits.positionAfterSkippingLeadingTrivia
+            process(violation: violation, forNode: node)
+        }
+
+        private func process(violation: AbsolutePosition, forNode node: ExprSyntaxProtocol) {
+            guard !node.isMemberOfATestClass(testParentClasses) else {
+                return
+            }
+            if let extendedClassName = node.extendedClassName() {
+                if testClasses.contains(extendedClassName) == false {
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift:158]: Can the explicit comparison with `false` be replaced?

**Review by SimplyDanny — COMMENTED** [review]
Looks good. I like how you achieve to traverse the AST only once!

Yet, like so often, I have some remarks ...

File: Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift [hunk 6]
```diff
@@ -64,7 +86,24 @@ struct NoMagicNumbersRule: SwiftSyntaxRule, OptInRule, ConfigurationProviderRule
...
+                        switch Int(degree) {
+                        case 0: return .right
+                        case ↓90: return .up
+                        case ↓180: return .left
+                        case -↓90: return .down
+                        default: return nil
+                        }
+                    }
+                }
+            }
```
[the remark this answers is not in the document]
Comment (mildm8nnered) [reply Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift:105]: I've simplified the tests considerably, in my next commit

File: Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift [hunk 7]
```diff
@@ -76,23 +115,67 @@ struct NoMagicNumbersRule: SwiftSyntaxRule, OptInRule, ConfigurationProviderRule
 private extension NoMagicNumbersRule {
     final class Visitor: ViolationsSyntaxVisitor {
         private let testParentClasses: Set<String>
+        private var testClasses: Set<String> = []
+        private var nonTestClasses: Set<String> = []
+        private var possibleViolations: [String: [ReasonedRuleViolation]] = [:]
```
[the remark this answers is not in the document]
Comment (mildm8nnered) [reply Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoMagicNumbersRule.swift:120]: That is definitely better - I did have to extend set to get the position -> violation mapping working like it does for Array

**Review by SimplyDanny — APPROVED** [review]

File: Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift [hunk 8]
```diff
@@ -127,3 +127,14 @@ public extension Array where Element == ReasonedRuleViolation {
         append(contentsOf: positions.map { ReasonedRuleViolation(position: $0) })
     }
 }
+
+/// Extension for sets of `ReasonedRuleViolation`s that provides the automatic conversion of
+/// `AbsolutePosition`s into `ReasonedRuleViolation`s (without a specific reason).
+public extension Set where Element == ReasonedRuleViolation {
```
Comment (mildm8nnered) [inline Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift:133]: it took me a while to work out how `AbsolutePosition`'s got "magically" transformed into `ReasonedRuleViolations` when they got added to `violations`.

**Comment by mildm8nnered** [comment]
> Looks good. I like how you achieve to traverse the AST only once!
> 
> Yet, like so often, I have some remarks ...

My heart always sinks a little at first, but the code ends up so much better for your feedback :-)

I wish I got code reviews like that in my day job.

File: Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift (hunk 8 above)
Comment (SimplyDanny) [reply Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift:133]: Well, is that really needed? You can carry around just the positions in `possibleViolations` and when they are eventually transferred into the `violations` array they will be converted to `ReasonedRuleViolations` as usual.

I think we should avoid the public extension if possible.

**Comment by SimplyDanny** [comment]
> > Looks good. I like how you achieve to traverse the AST only once!
> > Yet, like so often, I have some remarks ...
> 
> My heart always sinks a little at first, but the code ends up so much better for your feedback :-)
> 
> I wish I got code reviews like that in my day job.

Haha ... thank you for the kind feedback! I appreciate your continuous and well thought out contributions.

File: Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift (hunk 8 above)
Comment (mildm8nnered) [reply Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift:133]: Cool - I'll rework that later today or tomorrow

Comment (mildm8nnered) [reply Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift]: ok - should be good now I think ... I also converted the Examples to string literals, a la #5154

Comment (SimplyDanny) [reply Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift]: The string literals seemed to be cool. But unfortunately they break reporting of test failures right at the example code. I'll have to revert the change until we know how to make this work.

Comment (mildm8nnered) [reply Source/SwiftLintCore/Protocols/SwiftSyntaxRule.swift]: Dammit - reverted mine for now.
