### PR TITLE
Fix crash when using --config and --path with a Swift file

### LINKED ISSUE #1694: Crash when using --config and --path with a Swift file
Probably introduced on #1644. Reported by @valeriomazzeo on https://github.com/ashfurrow/danger-swiftlint/issues/49.

```
$ swiftlint lint --path foo.swift --config .swiftlint.yml
fatal error: Could not read configuration file at path '/Users/marcelofabri/dev/foo.swift/.swiftlint.yml': file /tmp/swiftlint-20170703-13452-ik99jk/Source/SwiftLintFramework/Models/Configuration.swift, line 167
/Users/marcelofabri/dev/foo.swift/.swiftlint.yml:File not found.
[1]    51731 illegal hardware instruction  swiftlint lint --path foo.swift --config .swiftlint.yml
```

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #1694

### CODE REVIEW

File: Source/SwiftLintFramework/Models/Configuration.swift [hunk 1]
```diff
@@ -112,7 +112,7 @@ public struct Configuration: Equatable {
     public init(path: String = Configuration.fileName, rootPath: String? = nil,
                 optional: Bool = true, quiet: Bool = false, enableAllRules: Bool = false, cachePath: String? = nil) {
         let fullPath: String
-        if let rootPath = rootPath {
+        if let rootPath = rootPath, rootPath.isDirectory() {
```
Comment (marcelofabri) [inline Source/SwiftLintFramework/Models/Configuration.swift]: I thought about using `rootPath.isSwiftFile()`, but I thought it'd be better to be safe.

File: Source/SwiftLintFramework/Models/Configuration.swift [hunk 2]
```diff
@@ -201,3 +201,18 @@ private func containsDuplicateIdentifiers(_ identifiers: [String]) -> Bool {
     }.joined(separator: "\n"))
     return true
 }
+
+private extension String {
+    func isDirectory() -> Bool {
+        var isDir: ObjCBool = false
+        if FileManager.default.fileExists(atPath: self, isDirectory:&isDir) {
```
Comment (jpsim) [inline Source/SwiftLintFramework/Models/Configuration.swift]: missing space: `isDirectory: &isDir`
