### PR TITLE
implicit_optional_initialization: add ignore_attributes support

### LINKED ISSUE #3998: `redundant_optional_initialization` warns on wrapped nilable property leading to compile errors
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

In the example

```swift
@propertyWrapper
struct Wrapper<T> {
    let name: String
    var wrappedValue: T

    init(wrappedValue value: T, _ name: String) {
        self.name = name
        self.wrappedValue = value
    }
}

struct Wrapped {
    @Wrapper("name")
    var flag: Bool? = nil // redundant_optional_initialization warn here
}
```

SwiftLint warns on the wrapped property assigned to `nil`. The property wrapper requires this explicit initialization, however. Removing the explicit assignment leads to a compile error.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint main.swift
Linting Swift files at paths main.swift
Linting 'main.swift' (1/1)
main.swift:14:20: warning: Redundant Optional Initialization Violation: Initializing an optional variable with nil is redundant. (redundant_optional_initialization)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint 0.47.1
* Homebrew
* Default configuration
* Xcode 13.4.1

### PR DESCRIPTION
**Pull request by theamodhshetty**
## Summary

Adds a targeted escape hatch for `implicit_optional_initialization` when explicit `= nil` is required by specific wrappers/attributes.

Fixes #3998.

## What changed

- Added `ignore_attributes` configuration to `implicit_optional_initialization`.
- Updated rule logic to skip style checks for declarations annotated with ignored attributes (for `style: always`).
- Added rule examples covering both ignored and non-ignored attribute cases.
- Added a changelog entry.

## Why

Some property wrappers/attributes require explicit optional initialization (`= nil`) to compile.
A previous broad approach (skip all custom attributes) was too permissive. This keeps behavior explicit and configurable.

## Validation

- `swift test --filter ImplicitOptionalInitializationRuleGeneratedTests`

## Example config

```yaml
implicit_optional_initialization:
  style: always
  ignore_attributes:
    - Wrapper
```

### CODE REVIEW

File: Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/ImplicitOptionalInitializationConfiguration.swift [hunk 1]
```diff
@@ -12,4 +12,6 @@ struct ImplicitOptionalInitializationConfiguration: SeverityBasedRuleConfigurati
     private(set) var severityConfiguration = SeverityConfiguration<Parent>(.warning)
     @ConfigurationElement(key: "style")
     private(set) var style: Style = .always
+    @ConfigurationElement(key: "ignore_attributes")
```
Comment (SimplyDanny) [inline Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/ImplicitOptionalInitializationConfiguration.swift:15]: I wonder if we could find a clearer name for this option. We don't ignore attributes but the variables to which the attributes are attached to.

Comment (theamodhshetty) [reply Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/ImplicitOptionalInitializationConfiguration.swift:15]: Good point. I kept `ignore_attributes` for consistency with other rules (e.g. `redundant_type_annotation`), but I am happy to rename if you prefer a different key.

**Comment by theamodhshetty** [comment]
Thanks for the catch on `style: never`.

I pushed 1da5182 to apply `ignore_attributes` checks for both styles (`always` and `never`) and added examples/tests for the `never` path.

**Comment by theamodhshetty** [comment]
Follow-up fix for the failing Registration step:

- ran rule/reporter registration and committed the generated default config update
- added ignore_attributes: [] under implicit_optional_initialization in Tests/IntegrationTests/Resources/default_rule_configurations.yml

Commit: d9e7257

File: Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/ImplicitOptionalInitializationConfiguration.swift (hunk 1 above)
Comment (SimplyDanny) [reply Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/ImplicitOptionalInitializationConfiguration.swift:15]: Thanks for the clarification. Consistency beats taste here.

**Comment by theamodhshetty** [comment]
Thanks for calling this out. I added explicit correction coverage to ensure the rewriter follows `ignore_attributes` for both styles:

- `style: never` + ignored attribute remains unchanged
- `style: always` + ignored attribute remains unchanged

I also ran:
`swift test --filter ImplicitOptionalInitializationRuleGeneratedTests`

and it passes locally.
