### PR TITLE
Fix `traling_comma` when using commas in comments.

### LINKED ISSUE #940: trailing_comma rule false positive for comments
Hi,

the following code will create a false positive in 0.13.1:

```
let example = [ "a",
                "b"
                // "c",
        ]
```

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #940

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/TrailingCommaRule.swift [hunk 1]
```diff
@@ -99,6 +102,22 @@ public struct TrailingCommaRule: ASTRule, ConfigurationProviderRule {
             )
         ]
     }
+
+    private func trailingCommaIndex(_ contents: String, file: File, offset: Int) -> Int? {
+        // swiftlint:disable:next force_try
+        let regex = try! NSRegularExpression(pattern: ",", options: [.ignoreMetacharacters])
+        let range = NSRange(location: 0, length: contents.characters.count)
```
Comment (jpsim) [inline Source/SwiftLintFramework/Rules/TrailingCommaRule.swift]: `contents.characters.count` is not always equal to `(contents as NSString).length`

File: Source/SwiftLintFramework/Rules/TrailingCommaRule.swift [hunk 2]
```diff
@@ -99,6 +102,22 @@ public struct TrailingCommaRule: ASTRule, ConfigurationProviderRule {
...
+        let ranges = regex.matches(in: contents, options: [], range: range).map { $0.range }
+
+        // skip commas in comments
+        return ranges.filter {
```
Comment (jpsim) [inline Source/SwiftLintFramework/Rules/TrailingCommaRule.swift]: I wonder if there's a more efficient way to do this...

**Comment by jpsim** [comment]
Thanks for tackling this!

File: Source/SwiftLintFramework/Rules/TrailingCommaRule.swift (hunk 2 above)
Comment (marcelofabri) [inline Source/SwiftLintFramework/Rules/TrailingCommaRule.swift]: I don't think this will be an issue since in most cases `ranges` would be empty. We could cache the regex tough.

Comment (jpsim) [inline Source/SwiftLintFramework/Rules/TrailingCommaRule.swift]: nah, I think it's fine as-is.

**Comment by jpsim** [comment]
Can you please rebase this so we can confirm it builds and passes tests on Linux?

**Comment by jpsim** [comment]
🎉
