### PR TITLE
Fix false positive in `multiline_parameters` rule when parameter is a closure has default value

### LINKED ISSUE #1912: multiline_parameters false positive when closures have default values
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report
When there is a default parameter for a closure, linting fails.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ echo "func function(\nparam1: Int,\nparam2: @escaping (Int, Int) -> Void = { _, _ in }\n) {\n}" | swiftlint lint --use-stdin
Loading configuration from '.swiftlint.yml'
<nopath>:1:6: warning: Multiline Parameters Violation: Functions and methods parameters should be either on the same line, or one per line. (multiline_parameters)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? **0.23.1**
* Installation method used (Homebrew, CocoaPods, building from source, etc)? **Homebrew or CocoaPods**, happens on both
* Paste your configuration file:

```yml
disabled_rules:
  - closing_brace
  - cyclomatic_complexity
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - nesting
  - notification_center_detachment
  - todo
  - trailing_comma
  - trailing_whitespace
  - type_name
  - weak_delegate
  - file_length
excluded:
  - Carthage
  - Pods
colon:
  flexible_right_spacing: true
line_length: 400
type_body_length:
  - 2048
  - 2048
function_body_length:
  - 400
  - 400
force_try:
  severity: warning
reporter: "xcode"
large_tuple:
  - 4
  - 4
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - multiline_parameters
  - overridden_super_call
  - prohibited_super_call
  - vertical_parameter_alignment_on_call
```

* Which Xcode version are you using (check `xcode-select -p`)? **9.0**

```swift
// This triggers a violation:
func function(
    param1: Int,
    param2: @escaping (Int, Int) -> Void = { _, _ in }
) {
}

func function(
    param1: Int,
    param2: @escaping (Int) -> Void = { _ in }
) {
}
```

### PR DESCRIPTION
**Pull request by ornithocoder**
Fixes #1912.

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/MultilineParametersRule.swift [hunk 1]
```diff
@@ -40,6 +40,7 @@ public struct MultilineParametersRule: ASTRule, OptInRule, ConfigurationProvider
         for structure in dictionary.substructure {
             guard
                 let structureOffset = structure.offset,
+                structure.typeName != nil,
```
Comment (marcelofabri) [inline Source/SwiftLintFramework/Rules/MultilineParametersRule.swift]: I don't think this is enough to fix the issue, as you can explicit use a type for the closure parameter:

```swift
func foo(param1: Int,
         param2: Bool,
         param3: @escaping (Int) -> Void = { (x: Int) in }) { }
```

Comment (ornithocoder) [reply Source/SwiftLintFramework/Rules/MultilineParametersRule.swift]: Yep. You're right. :'-( Do you see a not-so-dirty way to filter out these parameters within parameters?

Comment (marcelofabri) [reply Source/SwiftLintFramework/Rules/MultilineParametersRule.swift]: Can’t think about anything right now, but I vaguely remind dealing with this before. Maybe one or the rules has this implemented?

Comment (ornithocoder) [reply Source/SwiftLintFramework/Rules/MultilineParametersRule.swift]: I'll take a look. Thanks :-)

Comment (ornithocoder) [reply Source/SwiftLintFramework/Rules/MultilineParametersRule.swift]: I can check if the offset of the parameter isn't in the range of other parameters.

Comment (ornithocoder) [reply Source/SwiftLintFramework/Rules/MultilineParametersRule.swift]: Done. I've pushed another commit that checks the range of the parameter. If the parameter is in the bounds of another parameter, it rejects it. Something like this:  a 1, a 2, and a 3 would be
filtered out since they're inside parameter 3.

```
dictionary.substructure varParameters
----------------------------------------------------------------|
|        |---------| |---------| |----------------------------| |
|        | param 1 | | param 2 | | param 3: |a 1| |a 2| |a 3| | |
|        |---------| |---------| |----------------------------| |
----------------------------------------------------------------|
```
