### PR TITLE
Fix for #4788 - when disabled, `superfluous_disable_command` should not fire, even for invalid rule identifiers

### LINKED ISSUE #4788: `superfluous_disable` triggers for non existent rule names when `swiftlint:disable all` is in effect
### New Issue Checklist

- [x ] Updated SwiftLint to the latest version
- [ x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

```
// swiftlint:disable all
// swiftlint:disable non_existent_rule_name
```

No rules should be enabled, but `superfluous_disable` will still fire with `Superfluous Disable Command Violation: 'non_existent_rule_name' is not a valid SwiftLint rule; remove it from the disable command (superfluous_disable_command)`

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
% swiftlint Foo.swift 
Linting Swift files at paths Foo.swift
Linting 'Foo.swift' (1/1)
/tmp/Foo.swift:2:44: warning: Superfluous Disable Command Violation: 'non_existent_rule_name' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.50.3
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

none

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.

no

* Which Xcode version are you using (check `xcodebuild -version`)? 

Xcode 14.2
Build version 14C18

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// swiftlint:disable all
// swiftlint:disable non_existent_rule_name
```

### LINKED ISSUE #4798: superfluous_disable_command in a multiline comment generates multiple false alarms for `x is not a valid SwiftLint rule`
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Given the following input:

```
/*extension SidebarViewController {
    // swiftlint:disable cyclomatic_complexity
    // Make sure we're right clicking a menu entry
}
*/
```

`superfluous_disable_command` will generate multiple false positives.

#4791 fixes the case of this that occurs in Aerial purely by chance (see the osstools output on that PR), because the problem stretch of code there happens to contain the word `all` which is interpreted as suppress all rules. However #4791 does not fix the problem for the above case, or any other cases in general.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
% swiftlint lint --no-cache --use-stdin --enable-all-rules <<EOF
/*extension SidebarViewController {
    // swiftlint:disable cyclomatic_complexity
    // Make sure we're right clicking a menu entry
}
*/
EOF
The `anyobject_protocol` rule is now deprecated and will be completely removed in a future release.
<nopath>:5:3: warning: Superfluous Disable Command Violation: SwiftLint rule 'cyclomatic_complexity' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: 'sure' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: '//' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: 'a' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: 'clicking' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: 'entry' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: 'right' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: '}' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: 'menu' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: 'Make' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
<nopath>:5:3: warning: Superfluous Disable Command Violation: 'we're' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
Done linting! Found 11 violations, 0 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.50.3
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file: none

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
* Which Xcode version are you using (check `xcodebuild -version`)?

```
Xcode 14.2
Build version 14C18
```

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

See description above.

### PR DESCRIPTION
**Pull request by mildm8nnered**
Fixes #4788

When `superfluous_disable_command` is disabled, it should not fire, even for invalid rule identifiers.

Also fixes #4798 for Aerial - see the `This PR fixed a violation in Aerial` messages below, but only accidentally. See #4799 for more details, and a proper fix for #4798

### CODE REVIEW

**Comment by mildm8nnered** [comment]
Ah - I just noticed that there are a lot of `testSuperfluousDisableCommandsXXX` in `CommandTests` - I'll look at moving my tests there as well

**Comment by mildm8nnered** [comment]
and just saw all the false violations in the open source tests - back to the drawing board :-(

File: Tests/SwiftLintFrameworkTests/CommandTests.swift [hunk 1]
```diff
@@ -391,4 +392,18 @@ class CommandTests: XCTestCase {
             []
         )
     }
+
+    func testSuperfluousDisableCommandsDisabledWhenAllRulesDisabled() {
+        XCTAssertEqual(
+            violations(Example("// swiftlint:disable all\n// swiftlint:disable non_existent_rule_name\n")),
```
Comment (SimplyDanny) [inline Tests/SwiftLintFrameworkTests/CommandTests.swift:398]: I think it's a bit easier to read when using text blocks:
```suggestion
            violations(Example("""
                // swiftlint:disable all
                // swiftlint:disable non_existent_rule_name
            """)),
```

**Review by SimplyDanny — APPROVED** [review]
