### PR TITLE
Unused private coding keys

### LINKED ISSUE #2573: [unused_private_declaration] False positives on CodingKeys
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.30.0
* Installation method used: Homebrew
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - comma
  - line_length
  - todo
  - identifier_name

opt_in_rules: # some rules are only opt-in
#  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - AppName

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

analyzer_rules:
  - unused_private_declaration
  - unused_import

type_body_length:
  - 300 # warning
  - 500 # error

file_length:
  warning: 500
  error: 1200

type_name:
  max_length: # warning and error
    warning: 50
    error: 60

identifier_name:
  max_length: # warning and error
    warning: 60
    error: 70
  excluded: # excluded via string array
    - id
    - db

```

```swift
// This triggers a violation:
struct ResponseModel: Codable {
    let items: [Item]

    private enum CodingKeys: String, CodingKey { // <-- False 'unused_private_declaration' 
        case items = "ResponseItems"
    }
}
```

### PR DESCRIPTION
**Pull request by kimdv**
Fixes #2573

@jpsim i gave it a shot! 
Will add Changelog when it is good to avoid merge conflicts 😄

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/Lint/UnusedPrivateDeclarationRule.swift [hunk 1]
```diff
@@ -98,6 +122,14 @@ private extension File {
             if cursorInfo["key.overrides"] != nil {
                 return nil
             }
+
+            // Skip CodingKeys as they are used
+            if kind == .enum,
+                cursorInfo.name == "CodingKeys",
+                let annotatedDecl = cursorInfo["key.annotated_decl"] as? String,
+                annotatedDecl.contains(">CodingKey<") {
```
Comment (kimdv) [inline Source/SwiftLintFramework/Rules/Lint/UnusedPrivateDeclarationRule.swift]: It was the "best" way to find if it did conform to a protocol.

Comment (jpsim) [reply Source/SwiftLintFramework/Rules/Lint/UnusedPrivateDeclarationRule.swift]: On my phone right now so not 100% sure but you should be able to use `key.inheritedtypes` or `key.inherited_types` for this. If you search the SwiftLint or SourceKitten codebases you’ll find usage examples.

Comment (jpsim) [reply Source/SwiftLintFramework/Rules/Lint/UnusedPrivateDeclarationRule.swift]: Ah so that won't work because we just have `cursorInfo` here. However, we can strengthen this check by making sure it's the right `CodingKey` protocol.

```swift
annotatedDecl.contains("usr=\"s:s9CodingKeyP\">CodingKey<") {
```

**Comment by kimdv** [comment]
Thanks you very much for the last small fixes and changelog!

**Comment by jpsim** [comment]
Thanks for not minding 😊

I also think I fixed Danger on CI when running on forked branches.

**Comment by kimdv** [comment]
The analyzer is a powerful feature, and more power is in it! I'm looking forward to see what it can do! 🚀
