### PR TITLE
Fix regex for ignoring closure parameter on detecting return value

### LINKED ISSUE #324: valid_docs triggers a warning on tuples
Hi,

A warning is shown by the `valid_docs` rule when a function returns a tuple.
For example: 
```swift
	/**
	Awesome test function

	- returns: super tuple
	*/
	func tupleAsReturnValue() -> (r: CGFloat, g: CGFloat, b: CGFloat) {
		return (r: 1, g: 2, b: 3)
	}
```

There is no warning when the tuple is a parameter.

Thanks a lot for your work !
Regards

### PR DESCRIPTION
**Pull request by norio-nomura**
fix #324

### CODE REVIEW

File: Source/SwiftLintFramework/Rules/ValidDocsRule.swift [hunk 1]
```diff
@@ -135,6 +135,7 @@ public struct ValidDocsRule: Rule {
             "\n///- parameter param2: this is void too" +
             "\npublic func no(param: (Void -> Void)?, param2: String->Void) {}",
             "/// docs👨‍👩‍👧‍👧\n/// - returns: false\npublic func no() -> Bool { return false }",
+            "/// docs\n/// - returns: tuple\npublic func no() -> (Int, Int) {return (1, 2)}",
```
Comment (NachoSoto) [inline Source/SwiftLintFramework/Rules/ValidDocsRule.swift]: :heart_eyes:

**Comment by jpsim** [comment]
Awesome! Great work as always @norio-nomura

**Comment by norio-nomura** [comment]
:pray:
